// CSS track — 100 lessons for senior fullstack devs (C01–C100).

export const CSS_CURRICULUM = [
  { id: "c01", shortName: "C01", title: "Box Model" },
  { id: "c02", shortName: "C02", title: "box-sizing: border-box" },
  { id: "c03", shortName: "C03", title: "Margin Collapse" },
  { id: "c04", shortName: "C04", title: "Display Values" },
  { id: "c05", shortName: "C05", title: "Overflow" },
  { id: "c06", shortName: "C06", title: "Position: relative and absolute" },
  { id: "c07", shortName: "C07", title: "Position: fixed and sticky" },
  { id: "c08", shortName: "C08", title: "z-index and stacking context" },
  { id: "c09", shortName: "C09", title: "Flex: container and direction" },
  { id: "c10", shortName: "C10", title: "flex-wrap and gap" },
  { id: "c11", shortName: "C11", title: "justify-content" },
  { id: "c12", shortName: "C12", title: "align-items and align-content" },
  { id: "c13", shortName: "C13", title: "flex-grow, shrink, basis" },
  { id: "c14", shortName: "C14", title: "Flex shorthand and patterns" },
  { id: "c15", shortName: "C15", title: "Grid: container and template" },
  { id: "c16", shortName: "C16", title: "Grid template areas" },
  { id: "c17", shortName: "C17", title: "auto-fit and minmax()" },
  { id: "c18", shortName: "C18", title: "Centering (all methods)" },
  { id: "c19", shortName: "C19", title: "rem and em" },
  { id: "c20", shortName: "C20", title: "Viewport units (vw, vh, vmin, vmax)" },
  { id: "c21", shortName: "C21", title: "font-size and line-height" },
  { id: "c22", shortName: "C22", title: "text-overflow and white-space" },
  { id: "c23", shortName: "C23", title: "line-clamp" },
  { id: "c24", shortName: "C24", title: "Colors: hex, rgb, hsl" },
  { id: "c25", shortName: "C25", title: "currentColor and opacity" },
  { id: "c26", shortName: "C26", title: "background size, position, repeat" },
  { id: "c27", shortName: "C27", title: "Gradients (linear and radial)" },
  { id: "c28", shortName: "C28", title: "border-radius and box-shadow" },
  { id: "c29", shortName: "C29", title: "outline vs border" },
  { id: "c30", shortName: "C30", title: "transform: translate, scale, rotate" },
  { id: "c31", shortName: "C31", title: "transition basics" },
  { id: "c32", shortName: "C32", title: "@keyframes and animation" },
  { id: "c33", shortName: "C33", title: "Descendant and child selectors" },
  { id: "c34", shortName: "C34", title: ":nth-child and :not()" },
  { id: "c35", shortName: "C35", title: ":is() and :where()" },
  { id: "c36", shortName: "C36", title: "Attribute selectors" },
  { id: "c37", shortName: "C37", title: "Specificity" },
  { id: "c38", shortName: "C38", title: "@layer and cascade layers" },
  { id: "c39", shortName: "C39", title: "Media queries" },
  { id: "c40", shortName: "C40", title: "Container queries" },
  { id: "c41", shortName: "C41", title: "CSS custom properties (variables)" },
  { id: "c42", shortName: "C42", title: "::before and ::after" },
  { id: "c43", shortName: "C43", title: "min(), max(), clamp()" },
  { id: "c44", shortName: "C44", title: "aspect-ratio" },
  { id: "c45", shortName: "C45", title: "object-fit" },
  { id: "c46", shortName: "C46", title: "scroll-snap" },
  { id: "c47", shortName: "C47", title: ":has()" },
  { id: "c48", shortName: "C48", title: "Logical properties (margin-inline, etc.)" },
  { id: "c49", shortName: "C49", title: "focus-visible and a11y" },
  { id: "c50", shortName: "C50", title: "contain and content-visibility" },
  { id: "c51", shortName: "C51", title: "filter and backdrop-filter" },
  { id: "c52", shortName: "C52", title: "Pseudo-classes :hover :focus :active" },
  { id: "c53", shortName: "C53", title: "Multi-column layout (columns)" },
  { id: "c54", shortName: "C54", title: "Grid vs Flex: when to use which" },
  { id: "c55", shortName: "C55", title: "transform-origin" },
  { id: "c56", shortName: "C56", title: "animation fill-mode and direction" },
  { id: "c57", shortName: "C57", title: "prefers-reduced-motion" },
  { id: "c58", shortName: "C58", title: "color-scheme" },
  { id: "c59", shortName: "C59", title: "scroll-margin and scroll-padding" },
  { id: "c60", shortName: "C60", title: "Subgrid" },
  { id: "c61", shortName: "C61", title: "@supports" },
  { id: "c62", shortName: "C62", title: "will-change" },
  { id: "c63", shortName: "C63", title: "mix-blend-mode" },
  { id: "c64", shortName: "C64", title: "Multiple backgrounds" },
  { id: "c65", shortName: "C65", title: "conic-gradient" },
  { id: "c66", shortName: "C66", title: "Grid auto-placement" },
  { id: "c67", shortName: "C67", title: "Flex order" },
  { id: "c68", shortName: "C68", title: "align-self and justify-self" },
  { id: "c69", shortName: "C69", title: "Grid row/column span" },
  { id: "c70", shortName: "C70", title: "Sticky header/footer pattern" },
  { id: "c71", shortName: "C71", title: "Holy grail layout" },
  { id: "c72", shortName: "C72", title: "Card grid with auto-fit" },
  { id: "c73", shortName: "C73", title: "Responsive typography (clamp)" },
  { id: "c74", shortName: "C74", title: "fluid spacing with clamp" },
  { id: "c75", shortName: "C75", title: "fr unit and grid" },
  { id: "c76", shortName: "C76", title: "gap in Flex and Grid" },
  { id: "c77", shortName: "C77", title: "inset and position shorthand" },
  { id: "c78", shortName: "C78", title: "::placeholder and ::selection" },
  { id: "c79", shortName: "C79", title: "isolation and stacking" },
  { id: "c80", shortName: "C80", title: "Custom property fallbacks" },
  { id: "c81", shortName: "C81", title: "font-display" },
  { id: "c82", shortName: "C82", title: "letter-spacing and word-spacing" },
  { id: "c83", shortName: "C83", title: "text-align and vertical-align" },
  { id: "c84", shortName: "C84", title: "visibility and opacity" },
  { id: "c85", shortName: "C85", title: "cursor and pointer-events" },
  { id: "c86", shortName: "C86", title: "resize and overflow" },
  { id: "c87", shortName: "C87", title: "table layout" },
  { id: "c88", shortName: "C88", title: "list-style and counters" },
  { id: "c89", shortName: "C89", title: "break-inside and pagination" },
  { id: "c90", shortName: "C90", title: "mask and clip-path" },
  { id: "c91", shortName: "C91", title: "CSS custom properties in JS" },
  { id: "c92", shortName: "C92", title: "prefers-color-scheme (dark mode)" },
  { id: "c93", shortName: "C93", title: "print styles (@media print)" },
  { id: "c94", shortName: "C94", title: "Safe area insets" },
  { id: "c95", shortName: "C95", title: "Scroll-driven animations" },
  { id: "c96", shortName: "C96", title: "View transitions (View Transitions API)" },
  { id: "c97", shortName: "C97", title: "Container query units (cqw, cqh)" },
  { id: "c98", shortName: "C98", title: "Nesting (@nest / &)" },
  { id: "c99", shortName: "C99", title: "@scope" },
  { id: "c100", shortName: "C100", title: "Anchor positioning" },
];

export default CSS_CURRICULUM;
