/**
 * ID Module — planned catalog of generic assistance modules, organized by category.
 * This is the reference /match checks against before deciding whether to generate anything
 * new with Gemini. `tier` gates who a module is appropriate for:
 *   "foundational" — safe as an unsupervised JS "assist me" click from day one.
 *   "advanced"     — architecture/security-adjacent; reserve for a later cohort stage or
 *                    PJT/lead-level use, not an entry apprentice's unsupervised task.
 * Entries with status "planned" haven't been generated yet — generating one should move
 * it to "published" and register it in the Module Library (OneDev project 4).
 */

export const MODULE_CATALOG = [
  // --- Navigation & Layout ---
  { tag: "application-shell-layout", category: "Navigation & Layout", tier: "foundational",
    concept: "The persistent outer structure of an app — header, sidebar, content area — that every page renders inside.",
    build: "A shell with a top bar, a collapsible side panel, and a content slot that swaps per route.",
    keyTeaching: "Layout composition via children/slots; persistent vs. per-route UI.",
    codeElement: "React Router layout routes with <Outlet />; CSS Grid for the shell regions." },
  { tag: "sidebar-nav-drawer", category: "Navigation & Layout", tier: "foundational",
    concept: "A collapsible side panel listing navigation destinations, often toggled on smaller screens.",
    build: "A drawer that slides in/out and highlights the active destination.",
    keyTeaching: "Controlled open/close state; active-link styling from the current route.",
    codeElement: "useState for open/close; NavLink's active styling." },
  { tag: "breadcrumbs", category: "Navigation & Layout", tier: "foundational",
    concept: "A trail showing where the current page sits in a hierarchy, with each step clickable.",
    build: "A breadcrumb bar derived from the current route's nesting.",
    keyTeaching: "Deriving a list from route structure; rendering the last item as non-clickable.",
    codeElement: "Route matching to build a path array; map() over segments." },
  { tag: "mega-menu-nested-dropdown", category: "Navigation & Layout", tier: "foundational",
    concept: "A dropdown that reveals a larger panel of grouped options rather than a simple list.",
    build: "A nav item that opens a multi-column panel of links on hover/click.",
    keyTeaching: "Nested state for multi-level menus; closing on outside click.",
    codeElement: "onMouseEnter/onClick toggles; a document click listener to close." },
  { tag: "tabs", category: "Navigation & Layout", tier: "foundational",
    concept: "Switching between multiple views in the same space without navigating away.",
    build: "A tab bar that swaps which panel is visible.",
    keyTeaching: "Single 'active tab' state; conditional rendering of the matching panel.",
    codeElement: "useState for active tab id; role=\"tab\"/\"tabpanel\" ARIA pattern." },

  // --- Data Display & Visualization ---
  { tag: "info-summary-card", category: "Data Display", tier: "foundational",
    concept: "A bounded block presenting one unit of information clearly — title, value, optional action.",
    build: "A card showing a label, a value, and a small trend indicator.",
    keyTeaching: "Prop-driven rendering; conditional styling based on a value.",
    codeElement: "Destructured props; ternary for conditional className." },
  { tag: "data-grid-table", category: "Data Display", tier: "advanced",
    concept: "A table handling large datasets with sorting, column resizing, and virtualization.",
    build: "A sortable table backed by a large dataset, rendering only visible rows.",
    keyTeaching: "Virtualization to avoid rendering thousands of DOM nodes; sort state.",
    codeElement: "TanStack Table / TanStack Virtual; windowing." },
  { tag: "dashboard-composition", category: "Data Display", tier: "advanced",
    concept: "Assembling multiple independent widgets into one screen without them interfering with each other.",
    build: "A grid of cards/charts that each fetch and render independently.",
    keyTeaching: "Composition of many stateful children; avoiding one widget re-rendering its siblings.",
    codeElement: "Component composition; React.memo on sibling widgets." },
  { tag: "tree-view", category: "Data Display", tier: "foundational",
    concept: "A nested, expandable/collapsible representation of hierarchical data.",
    build: "A folder-style tree where each node can expand to show children.",
    keyTeaching: "Recursive component rendering; per-node expanded state.",
    codeElement: "A component that renders itself for each child node." },
  { tag: "kanban-board", category: "Data Display", tier: "foundational",
    concept: "Columns of cards that can be moved between columns to represent status changes.",
    build: "Columns (e.g. To Do / In Progress / Done) with draggable cards between them.",
    keyTeaching: "Lifting state up so a drag updates the shared list; drop-target detection.",
    codeElement: "HTML5 drag events or a drag library; state keyed by column." },

  // --- Data Input & Forms ---
  { tag: "multi-step-wizard", category: "Data Input & Forms", tier: "foundational",
    concept: "A form split across multiple screens, with progress tracked and data preserved between steps.",
    build: "A 3-step form where later steps can see earlier answers, with a progress indicator.",
    keyTeaching: "Lifting form state above the step components; a currentStep index.",
    codeElement: "useState holding the whole form's data; conditional step rendering." },
  { tag: "rich-text-editor", category: "Data Input & Forms", tier: "advanced",
    concept: "An editable area supporting formatted text (bold, lists, links) rather than plain text.",
    build: "A small WYSIWYG editor with a formatting toolbar.",
    keyTeaching: "contentEditable or a structured document model; serializing to HTML/JSON.",
    codeElement: "Tiptap/Slate/Lexical; toolbar commands dispatched to the editor instance." },
  { tag: "drag-drop-file-upload", category: "Data Input & Forms", tier: "foundational",
    concept: "Letting a user drop files onto a target area instead of only using a file picker.",
    build: "A drop zone that accepts files by drag or click, showing upload progress.",
    keyTeaching: "Drag event handlers; preventing the browser's default 'open file' behavior.",
    codeElement: "onDragOver/onDrop with e.preventDefault(); FormData for upload." },
  { tag: "autocomplete-combobox", category: "Data Input & Forms", tier: "foundational",
    concept: "A text input that filters and suggests options as the user types.",
    build: "A search box that filters a list of options and lets you pick one.",
    keyTeaching: "Debounced filtering; keyboard navigation of suggestions.",
    codeElement: "useState for query + filtered list; onKeyDown for arrow/enter." },
  { tag: "date-time-range-picker", category: "Data Input & Forms", tier: "foundational",
    concept: "Selecting a start and end date/time as a single bounded range.",
    build: "A calendar picker that lets you select a start then an end date.",
    keyTeaching: "Two-part state (start/end); validating end is after start.",
    codeElement: "useState for {start, end}; a date library for comparisons." },
  { tag: "form-validation-architecture", category: "Data Input & Forms", tier: "advanced",
    concept: "Defining validation rules once and deriving both runtime checks and static types from the same schema, so they can't drift apart.",
    build: "A form whose validation rules and TypeScript types both come from one schema definition.",
    keyTeaching: "Schema-first design; async validation (e.g. checking uniqueness) without janky UX.",
    codeElement: "Zod/Yup schema; zodResolver with a form library; z.infer for types; debounced async refine." },

  // --- Search & Filtering ---
  { tag: "command-palette-omnisearch", category: "Search & Filtering", tier: "advanced",
    concept: "A keyboard-triggered overlay for quickly finding and jumping to actions or pages.",
    build: "A Cmd/Ctrl+K overlay that searches a list of commands and executes the selected one.",
    keyTeaching: "Global keyboard shortcut handling; fuzzy filtering.",
    codeElement: "A global keydown listener; a lightweight fuzzy-match function." },
  { tag: "faceted-filter-panel", category: "Search & Filtering", tier: "foundational",
    concept: "Multiple independent filter controls that combine to narrow a result set.",
    build: "A panel with several checkbox groups that together filter a list.",
    keyTeaching: "Combining multiple filter states into one derived result list.",
    codeElement: "useMemo deriving filtered results from several state values." },

  // --- Feedback & Overlays ---
  { tag: "modal-dialog", category: "Feedback & Overlays", tier: "foundational",
    concept: "A window that overlays the page and captures focus until dismissed.",
    build: "A dialog that opens on a button click and traps keyboard focus while open.",
    keyTeaching: "Portal rendering; focus trapping; closing on Escape/outside click.",
    codeElement: "createPortal; a focus-trap pattern; onKeyDown for Escape." },
  { tag: "toast-notification", category: "Feedback & Overlays", tier: "foundational",
    concept: "A brief, non-blocking message that appears and automatically disappears.",
    build: "A toast that appears on an action and fades out after a few seconds.",
    keyTeaching: "Timed state removal; stacking multiple toasts.",
    codeElement: "setTimeout to auto-dismiss; a list of active toasts in state." },
  { tag: "context-menu", category: "Feedback & Overlays", tier: "foundational",
    concept: "A menu that appears at the cursor position in response to a right-click or long-press.",
    build: "A right-click menu with a few actions, positioned at the click location.",
    keyTeaching: "Preventing the browser's default context menu; positioning from event coordinates.",
    codeElement: "onContextMenu with e.preventDefault(); clientX/clientY for position." },
  { tag: "skeleton-shimmer-loader", category: "Feedback & Overlays", tier: "foundational",
    concept: "A placeholder shape shown while real content is loading, to reduce perceived wait time.",
    build: "A card that shows a shimmering placeholder until its data arrives.",
    keyTeaching: "Loading-state branching; matching the skeleton's shape to the real content.",
    codeElement: "Conditional rendering on an isLoading flag; a CSS shimmer animation." },
  { tag: "error-boundary-fallback", category: "Feedback & Overlays", tier: "advanced",
    concept: "Catching a render-time error in part of the tree so it doesn't crash the whole app.",
    build: "A section of the app that shows a 'retry' fallback instead of a blank screen if it errors.",
    keyTeaching: "Error boundaries only catch render errors, not event handlers; recoverable fallback UI.",
    codeElement: "An ErrorBoundary class component (or react-error-boundary); componentDidCatch." },

  // --- Identity & Security ---
  { tag: "sso-login-panel", category: "Identity & Security", tier: "advanced",
    concept: "A login screen that redirects to a third-party identity provider instead of collecting a password directly.",
    build: "A login button that starts an OAuth redirect flow and handles the callback.",
    keyTeaching: "Redirect-based auth flow; handling the return callback and storing session state.",
    codeElement: "OAuth authorization-code flow; a callback route that exchanges the code." },
  { tag: "rbac-matrix", category: "Identity & Security", tier: "advanced",
    concept: "Showing or hiding UI and gating actions based on a user's assigned role(s).",
    build: "A screen where certain buttons only appear for certain roles.",
    keyTeaching: "Centralizing permission checks instead of scattering role checks everywhere.",
    codeElement: "A can(role, action) helper; conditional rendering driven by it." },
  { tag: "token-lifecycle-management", category: "Identity & Security", tier: "advanced",
    concept: "Silently refreshing an auth token before it expires, and handling refresh failure gracefully.",
    build: "A fetch wrapper that retries a request after refreshing an expired token, or redirects to login if refresh fails.",
    keyTeaching: "Where NOT to store sensitive tokens (localStorage is XSS-exposed); refresh-then-retry flow.",
    codeElement: "Fetch/HTTP client interceptors for 401 handling; HttpOnly cookies or in-memory storage." },
  { tag: "xss-csrf-defense", category: "Identity & Security", tier: "advanced",
    concept: "Preventing injected scripts from running and preventing forged cross-site requests.",
    build: "A comments feature that sanitizes user content before rendering and includes an anti-CSRF token on submit.",
    keyTeaching: "Never trust user-generated HTML; state-changing requests need CSRF protection even with cookie auth.",
    codeElement: "DOMPurify for sanitization; Content-Security-Policy headers; anti-CSRF token middleware." },

  // --- Rendering Strategy & Data Fetching ---
  { tag: "rendering-mode-selection", category: "Rendering Strategy", tier: "advanced",
    concept: "Choosing where a page's HTML gets built — on the server per request, at build time, or in the browser — based on freshness and SEO needs.",
    build: "Comparing the same page rendered client-side vs. server-side and noticing the hydration difference.",
    keyTeaching: "CSR vs SSR vs SSG vs ISR trade-offs; hydration mismatches between server and client output.",
    codeElement: "Framework-level route loaders / static generation config." },
  { tag: "server-vs-client-state", category: "Rendering Strategy", tier: "advanced",
    concept: "Treating data fetched from a server (cacheable, can go stale) differently from local UI state (form inputs, toggles).",
    build: "A screen that fetches a list with automatic caching and refetch, alongside a purely local filter toggle.",
    keyTeaching: "Not putting server data in a general-purpose store and hand-rolling cache invalidation.",
    codeElement: "TanStack Query/SWR for server state; useState/local store for UI-only state." },
  { tag: "optimistic-updates", category: "Rendering Strategy", tier: "advanced",
    concept: "Updating the UI immediately on user action, before the server confirms, then rolling back on failure.",
    build: "A like button that toggles instantly and reverts if the request fails.",
    keyTeaching: "Perceived performance vs. correctness trade-off; rollback on error.",
    codeElement: "A mutation library's optimistic-update/rollback hooks." },

  // --- Performance Engineering ---
  { tag: "code-splitting-lazy-loading", category: "Performance", tier: "advanced",
    concept: "Splitting the JS bundle so a view only downloads the code it actually needs.",
    build: "A heavy component (e.g. a chart) that only loads when its section becomes visible.",
    keyTeaching: "Dynamic import vs. static import; loading state while a chunk downloads.",
    codeElement: "React.lazy() + Suspense; dynamic import()." },
  { tag: "memoization-rerender-control", category: "Performance", tier: "advanced",
    concept: "Preventing a component from re-rendering when unrelated state elsewhere changes.",
    build: "A dashboard where updating one widget's state doesn't re-render its siblings.",
    keyTeaching: "When memoization actually helps vs. when it's premature optimization.",
    codeElement: "React.memo, useMemo, useCallback; profiling to confirm it mattered." },
  { tag: "core-web-vitals", category: "Performance", tier: "advanced",
    concept: "Monitoring and optimizing for the metrics that affect both perceived speed and search ranking.",
    build: "A page audited for layout shift, then fixed by reserving image/skeleton dimensions.",
    keyTeaching: "LCP, INP, and CLS — what each measures and one concrete fix per metric.",
    codeElement: "The web-vitals package; explicit width/height or aspect-ratio on media." },

  // --- Accessibility ---
  { tag: "keyboard-navigation", category: "Accessibility", tier: "foundational",
    concept: "Making every interactive element reachable and operable without a mouse.",
    build: "A custom dropdown operable entirely with Tab, Enter, Escape, and arrow keys.",
    keyTeaching: "tabIndex and visible focus states; Escape-to-close, arrow-key list movement.",
    codeElement: "onKeyDown handlers; :focus-visible styling." },
  { tag: "screen-reader-semantics", category: "Accessibility", tier: "advanced",
    concept: "Using correct roles and labels so assistive technology announces components meaningfully.",
    build: "A custom dropdown that announces as 'combobox, expanded' to a screen reader, not silently.",
    keyTeaching: "Semantic HTML over div-with-onClick; ARIA roles and live regions.",
    codeElement: "role, aria-expanded, aria-live; automated checks with axe-core." },

  // --- CSS & Design System Architecture ---
  { tag: "design-token-pipeline", category: "Design System", tier: "advanced",
    concept: "Defining colors, spacing, and typography once as tokens, then propagating them everywhere consistently.",
    build: "A small set of design tokens consumed as CSS variables across two differently-styled components.",
    keyTeaching: "Single source of truth for design values; where drift between design and code comes from.",
    codeElement: "A token JSON pipeline into CSS custom properties or a theme config." },
  { tag: "responsive-container-layout", category: "Design System", tier: "advanced",
    concept: "Adapting a layout to its own container's size, not just the viewport — needed for widgets reused in different contexts.",
    build: "A card that reflows its internal layout based on the width of whatever panel it's placed in.",
    keyTeaching: "Viewport-based responsiveness vs. container-based; why a reusable widget needs the latter.",
    codeElement: "CSS Grid/Flexbox; @container queries; clamp() for fluid sizing." },
  { tag: "component-api-design", category: "Design System", tier: "advanced",
    concept: "Designing a component's props/slots to be flexible enough for real use cases without inviting misuse.",
    build: "A Select component built as composable parts instead of one prop-heavy monolith.",
    keyTeaching: "Compound components; controlled vs. uncontrolled variants.",
    codeElement: "A compound-component pattern (<Select><Select.Option/></Select>)." },

  // --- Testing & Quality ---
  { tag: "component-unit-testing", category: "Testing", tier: "foundational",
    concept: "Verifying a single component renders correctly and responds to interaction, in isolation.",
    build: "A test that renders a button component and asserts a click fires the expected behavior.",
    keyTeaching: "Testing behavior/output, not implementation details; simulating real interaction.",
    codeElement: "Vitest/Jest + React Testing Library; userEvent over fireEvent." },
  { tag: "visual-regression-testing", category: "Testing", tier: "advanced",
    concept: "Catching unintended visual changes by diffing screenshots against a known-good baseline.",
    build: "A snapshot test that fails when a CSS change silently breaks a card's layout.",
    keyTeaching: "What a pixel-diff catches that a behavioral test doesn't.",
    codeElement: "Chromatic or Playwright screenshot testing." },
  { tag: "e2e-testing", category: "Testing", tier: "advanced",
    concept: "Simulating a full user journey across multiple pages to catch integration failures unit tests miss.",
    build: "A test that logs in, navigates to a form, submits it, and asserts the result page.",
    keyTeaching: "What only shows up when real pieces are wired together, not mocked individually.",
    codeElement: "Playwright or Cypress running against a real or mocked backend." },

  // --- Build Tooling & Delivery ---
  { tag: "monorepo-module-boundaries", category: "Build Tooling", tier: "advanced",
    concept: "Structuring shared packages so they're versioned and consumed cleanly across multiple apps without circular dependencies.",
    build: "Two apps consuming one shared UI package through a defined public export surface.",
    keyTeaching: "Why an unrestricted internal package surface causes circular-dependency pain later.",
    codeElement: "Workspace tooling (e.g. pnpm workspaces) with a controlled package exports field." },
  { tag: "feature-flags", category: "Build Tooling", tier: "advanced",
    concept: "Shipping code to production behind a toggle, enabling gradual rollout or instant rollback without a redeploy.",
    build: "A new UI section that only renders when a flag is enabled, togglable without shipping new code.",
    keyTeaching: "Decoupling deploy from release; what a flag check looks like in real rendering code.",
    codeElement: "A feature-flag SDK; conditional rendering gated on flag evaluation." },
];
