// ─── INPACT — Batch 1: JavaScript Fundamentals ────────────────────────────────

export const JS_FUNDAMENTALS_CURRICULUM = [
  { id: "jsf01", file: "inpact_jsf01_engine", shortName: "JS — DESTRUCTURING",   title: "Variables, Destructuring & Spread",     topics: ["var/let/const scoping", "Array destructuring", "Object destructuring + rename", "Rest in destructuring", "Spread clone/merge/override", "Prop passthrough pattern"], why: "The foundation of modern JS. You'll use destructuring and spread in every React component and API handler." },
  { id: "jsf02", file: "inpact_jsf02_engine", shortName: "JS — FUNCTIONS",       title: "Functions — Arrow, Closures & HOF",    topics: ["Arrow function forms", "Lexical this", "Closures + private state", "Higher-order functions", "compose / pipe", "IIFE", "Currying + partial application"], why: "Functions are values. Closures and HOFs power React hooks and every functional pattern you'll write." },
  { id: "jsf03", file: "inpact_jsf03_engine", shortName: "JS — ASYNC",           title: "Promises & Async/Await",               topics: ["Promise constructor", ".then/.catch/.finally", "async/await", "Promisifying callbacks", "Promise.all vs allSettled", "Promise.race + timeout pattern", "Promise.any"], why: "Every fetch, every API call, every async UI update. Non-negotiable for real applications." },
  { id: "jsf04", file: "inpact_jsf04_engine", shortName: "JS — ARRAYS",          title: "Arrays & Iterators",                   topics: ["map/filter/reduce pipeline", "find/some/every/findIndex", "reduce → object (normalize)", "Mutating vs non-mutating", "flat + flatMap", "Custom iterables with Symbol.iterator"], why: "Data in, data out. List rendering and state updates are all array operations." },
  { id: "jsf05", file: "inpact_jsf05_engine", shortName: "JS — CLASSES",         title: "Objects, Prototypes & Classes",        topics: ["Prototype chain lookup", "Full ES6 class anatomy", "#private fields", "extends + super", "Object.keys/entries/fromEntries/freeze", "this binding fixes"], why: "Classes and prototypes underpin libraries and legacy code. Know how this and inheritance work." },
  { id: "jsf06", file: "inpact_jsf06_engine", shortName: "JS — MODULES",         title: "Modules — ESM & CommonJS",             topics: ["Named vs default exports", "Barrel files / re-exports", "Dynamic import()", "CommonJS require/module.exports", "ESM ↔ CJS interop rules"], why: "Every import/export you write. ESM is the standard; CJS interop is still everywhere." },
  { id: "jsf07", file: "inpact_jsf07_engine", shortName: "JS — ERRORS",          title: "Error Handling & Debugging",           topics: ["try/catch/finally sync+async", "Custom Error subclasses", "Global unhandledRejection handlers", "console.table/.group/.time/.trace", "Production error boundary wrapper"], why: "Robust apps handle failure. Debugging and error boundaries start here." },
  { id: "jsf08", file: "inpact_jsf08_engine", shortName: "JS — DATA STRUCTURES", title: "Map, Set, WeakMap & Symbols",          topics: ["Map with any-type keys", "Set for dedup + union/intersection", "WeakMap for memory-safe caching", "Symbol unique keys", "Symbol.toPrimitive/.iterator", "EventEmitter using Map+Set"], why: "When plain objects aren't enough. Caching, dedup, and safe metadata use these." },
  { id: "jsf09", file: "inpact_jsf09_engine", shortName: "JS — GENERATORS",      title: "Generators, Iterators & Proxy",        topics: ["function* and yield", "Lazy generator pipelines", "Async generators for pagination/SSE", "Proxy get/set/has traps", "Reflect.get/set", "Reactive state with Proxy"], why: "Lazy data, reactive patterns, and framework internals. Senior-level JS toolkit." },
  { id: "jsf10", file: "inpact_jsf10_engine", shortName: "JS — PERFORMANCE",     title: "Performance, Memory & Event Loop",     topics: ["Event loop: stack/microtask/macrotask", "debounce + throttle from scratch", "Memory leak patterns + fixes", "requestAnimationFrame for animation", "Web Workers for heavy computation"], why: "Understand why UI janks, how to smooth it, and when to offload work." },
  { id: "jsf12", file: "inpact_jsf12_engine", shortName: "JS — REGEX",           title: "Regular Expressions",                   why: "Validation, parsing, search — regex is in every layer of a real app." },
  { id: "jsf13", file: "inpact_jsf13_engine", shortName: "JS — NUMBERS & DATES", title: "Numbers, Math, Date & Intl",            why: "Price formatting, dates, i18n — number and date work in every feature." },
  { id: "jsf14", file: "inpact_jsf14_engine", shortName: "JS — COERCION",        title: "Type Coercion, Equality & Truthy/Falsy", why: "Coercion rules are the root cause of hundreds of real bugs — know them cold." },
  { id: "jsf15", file: "inpact_jsf15_engine", shortName: "JS — SCOPE",           title: "Scope, Hoisting & the TDZ",             why: "Closure bugs, TDZ errors, hoisting surprises — daily debugging scenarios." },
];

export default JS_FUNDAMENTALS_CURRICULUM;
