import createINPACTEngine from "../inpact_engine_shared";

const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #20 (React Patterns)", title: "Component Composition", body: "Composition is how React applications are built at scale. Instead of one large component that does everything, you build small focused components and compose them together — each responsible for one thing, each passing data down through props or children. In this lesson you'll build a multi-level component hierarchy for the shipment dashboard: a page shell, a list, a card, and a badge — each composed from the others.", usecase: "A shipment dashboard page has a header, a filter bar, and a list of cards. Each card has a status badge. These are four distinct concerns — four components. Composing them means changing the badge design touches only the badge, changing the filter touches only the filter, and the page shell can be reused for other data types without modification." } },
  {
  id: "prereqs",
  type: "prereqs",
  phase: "Prerequisites",
  items: [
    {
      lesson: 1,
      label: "JSX — The Full Language",
      reason: "Complete Lesson 1 (JSX — The Full Language) first — it is a prerequisite on the React-TS track for this lesson.",
    },
    {
      lesson: 7,
      label: "Props + Interface",
      reason: "Complete Lesson 7 (Props + Interface) first — it is a prerequisite on the React-TS track for this lesson.",
    },
    {
      lesson: 8,
      label: "Optional Props + Defaults",
      reason: "Complete Lesson 8 (Optional Props + Defaults) first — it is a prerequisite on the React-TS track for this lesson.",
    },
    {
      lesson: 9,
      label: "children Prop + ReactNode",
      reason: "Complete Lesson 9 (children Prop + ReactNode) first — it is a prerequisite on the React-TS track for this lesson.",
    },
  ],
},
{ id: "objectives", type: "objectives", phase: "Objectives", items: [
    "Build a multi-level component hierarchy where each component has a single responsibility",
    "Pass data from a parent down to grandchildren through intermediate components",
    "Use the children prop to build layout shells agnostic to their content",
    "Understand when to lift a component into a reusable abstraction",
    "Recognise prop drilling and understand when it becomes a problem",
  ]},
  {
    id: "step1", type: "question", phase: "Step 1 of 5",
    paal: "Build a StatusBadge component that accepts a status (ShipmentStatus) and renders a span with a dynamic className and the status text.",
    hint: "StatusBadge is the leaf component — minimum props, fully reusable. Use a template literal for the className.",
    example_code: "const PriorityBadge = ({ priority }: { priority: Priority }): JSX.Element => (\n  <span className={`badge badge--${priority}`}>{priority}</span>\n);",
    think_prompt: "StatusBadge should know nothing about shipments or pages — only how to render a status value as a badge. What is the minimum props interface it needs?",
    mc_options: [
      "Props: shipment (ShipmentRecord) — pass the whole record, render just the status",
      "Props: status (ShipmentStatus) — pass only what the component needs to render",
      "Props: none — read status from context",
    ],
    mc_correct_option: "Props: status (ShipmentStatus) — pass only what the component needs to render",
    mc_anchor: "StatusBadge only needs the status value — passing the full ShipmentRecord couples it to the data shape unnecessarily. If ShipmentRecord changes, StatusBadge would need updating even if status hasn't changed. Minimum interface = maximum reusability.",
    why_this_matters: "Leaf components with minimum props interfaces are the most reusable. StatusBadge can render any status — from a shipment, a route, a warehouse — because it only knows about ShipmentStatus, not ShipmentRecord.",
    answer_keywords: ["StatusBadge", "status", "ShipmentStatus", "span", "badge--"],
    seed_code: "type ShipmentStatus = 'active' | 'delayed' | 'delivered';",
    starter_code: "type ShipmentStatus = 'active' | 'delayed' | 'delivered';\n\n// build StatusBadge here\n// props: status (ShipmentStatus)\n// renders: <span className=\"badge badge--{status}\">{status}</span>",
    feedback_correct: "Exactly — StatusBadge accepts only what it needs, renders a single element, and is fully reusable.",
    feedback_partial: "Close — make sure the className uses a template literal: `badge badge--${status}`, giving CSS a hook per status.",
    feedback_wrong: "Define `interface StatusBadgeProps { status: ShipmentStatus; }`. Return `<span className={\\`badge badge--${status}\\`}>{status}</span>`.",
    expected: "type ShipmentStatus = 'active' | 'delayed' | 'delivered';\n\ninterface StatusBadgeProps {\n  status: ShipmentStatus;\n}\n\nconst StatusBadge = ({ status }: StatusBadgeProps): JSX.Element => (\n  <span className={`badge badge--${status}`}>{status}</span>\n);",
    analog_example: "const PriorityTag = ({ priority }: { priority: Priority }): JSX.Element => (\n  <span className={`tag tag--${priority}`}>{priority}</span>\n);",
    deepDiveLabel: "Minimum props = maximum reusability — but what if StatusBadge needs its own label formatting?",
    deepDive: {
      hook: "StatusBadge renders the status value as text: 'active'. The design team wants 'Active' — typescript arrow . Then 'delayed' becomes 'In Transit'. Should the badge handle its own label mapping?",
      pain: "⚠️ **Lesson:** Should StatusBadge handle label formatting internally — or should the parent pass a formatted label? Where does data-to-display mapping live?",
      mentalModel: "Two approaches:\n1. **Child maps**: Badge has a label lookup table. Accepts status, derives label. Good when the label is always the same everywhere.\n2. **Parent maps**: Parent passes `label={STATUS_LABELS[status]}`. Good when labels vary by context or locale.\n\n`Record<ShipmentStatus, string>` gives exhaustiveness — TypeScript errors if a new status is added without a label.",
      discover: "```tsx\n// ✅ child maps — canonical label\nconst STATUS_LABELS: Record<ShipmentStatus, string> = {\n  active: 'Active',\n  delayed: 'In Transit',\n  delivered: 'Delivered',\n};\nconst StatusBadge = ({ status }: StatusBadgeProps): JSX.Element => (\n  <span className={`badge badge--${status}`}>{STATUS_LABELS[status]}</span>\n);\n```",
      quickRules: "- ✅ child maps: label is always the same (canonical)\n- ✅ parent maps: label varies by context or locale\n- ✅ Record<UnionType, string>: exhaustive, TypeScript errors if status added without label",
      watchOut: "👀 **Watch out:** `Record<ShipmentStatus, string>` gives a TypeScript error if you add a new status to the union but forget to add it to the label map — same exhaustiveness check as assertNever.",
      dryRun: "🔁 **Think:** STATUS_LABELS is `{ active: 'Active', delayed: 'In Transit', delivered: 'Delivered' }`. A new status 'pending' is added to the union. TypeScript: error on the Record definition — what does it say?",
      build: "**Learning focus:** Build the leaf badge with a minimum props interface — understanding where data-to-display mapping responsibility belongs.",
    }
  },
  {
    id: "step2", type: "question", phase: "Step 2 of 5",
    paal: "Build ShipmentCard that accepts a ShipmentRecord and renders shipmentId, destination, and a StatusBadge for the status.",
    hint: "ShipmentCard uses StatusBadge internally — it doesn't expose badge props to its own callers. Pass shipment.status to StatusBadge.",
    example_code: "const OrderCard = ({ order }: { order: OrderRecord }): JSX.Element => (\n  <div className=\"card\">\n    <p>{order.orderId}</p>\n    <PriorityTag priority={order.priority} />\n  </div>\n);",
    think_prompt: "ShipmentCard knows about shipments. StatusBadge knows about status display. How do you wire them — and what props does ShipmentCard expose?",
    mc_options: [
      "Accept shipmentId, destination, status separately and pass status to StatusBadge",
      "Accept a ShipmentRecord object and extract status internally to pass to StatusBadge",
      "Accept a StatusBadge element as a prop and render it",
    ],
    mc_correct_option: "Accept a ShipmentRecord object and extract status internally to pass to StatusBadge",
    mc_anchor: "Passing the full record keeps ShipmentCard's interface clean — one prop. The card extracts what it needs and passes the minimal required prop to StatusBadge. Passing fields separately requires updating ShipmentCard whenever ShipmentRecord changes.",
    why_this_matters: "ShipmentCard owns the ShipmentRecord data. StatusBadge owns status display. ShipmentCard extracts status and passes it — the badge never needs to know about records. This clean boundary makes each component independently testable.",
    answer_keywords: ["ShipmentRecord", "ShipmentCard", "StatusBadge", "status", "shipmentId", "destination"],
    seed_code: "type ShipmentStatus = 'active' | 'delayed' | 'delivered';\ninterface ShipmentRecord { shipmentId: string; destination: string; status: ShipmentStatus; }\ninterface StatusBadgeProps { status: ShipmentStatus; }\nconst StatusBadge = ({ status }: StatusBadgeProps): JSX.Element => (\n  <span className={`badge badge--${status}`}>{status}</span>\n);",
    starter_code: "type ShipmentStatus = 'active' | 'delayed' | 'delivered';\ninterface ShipmentRecord { shipmentId: string; destination: string; status: ShipmentStatus; }\nconst StatusBadge = ({ status }: { status: ShipmentStatus }): JSX.Element => (\n  <span className={`badge badge--${status}`}>{status}</span>\n);\n\n// build ShipmentCard here\n// props: shipment (ShipmentRecord)\n// renders: shipmentId, destination, and a StatusBadge",
    feedback_correct: "Exactly — ShipmentCard accepts the full record and passes shipment.status to StatusBadge. The badge is used without the caller needing to know about it.",
    feedback_partial: "Close — make sure ShipmentCard accepts the full ShipmentRecord (not individual fields) and uses StatusBadge with `status={shipment.status}`.",
    feedback_wrong: "Define `interface ShipmentCardProps { shipment: ShipmentRecord; }`. Render `{shipment.shipmentId}`, `{shipment.destination}`, and `<StatusBadge status={shipment.status} />`.",
    expected: "interface ShipmentCardProps {\n  shipment: ShipmentRecord;\n}\n\nconst ShipmentCard = ({ shipment }: ShipmentCardProps): JSX.Element => (\n  <div className=\"card\">\n    <p>{shipment.shipmentId}</p>\n    <p>{shipment.destination}</p>\n    <StatusBadge status={shipment.status} />\n  </div>\n);",
    analog_example: "const OrderCard = ({ order }: { order: OrderRecord }): JSX.Element => (\n  <div><p>{order.orderId}</p><PriorityTag priority={order.priority} /></div>\n);",
    deepDiveLabel: "ShipmentCard passes status to StatusBadge — is this prop drilling?",
    deepDive: {
      hook: "A colleague says passing status from ShipmentCard to StatusBadge is prop drilling. You say it's just one level. They say the problem isn't the current level — it's when the badge moves three levels deeper. When does prop passing become a problem?",
      pain: "⚠️ **Lesson:** Prop drilling is passing data through intermediate components that don't use it. ShipmentCard uses shipment to render its own content AND derives status for StatusBadge. Is this prop drilling?",
      mentalModel: "**Not prop drilling**: Component uses the prop it receives AND passes a derived value down. ShipmentCard uses shipment (renders id, destination) and passes shipment.status to badge. ✅\n\n**Prop drilling**: Component receives a prop only to pass to a child — it doesn't use it. PageShell receives userId only to pass to Header only to pass to UserAvatar. ❌\n\n**Solutions**: (1) Composition — pass the whole component, not its props. (2) Context — broadcast to any descendant (Lesson 47).",
      discover: "```tsx\n// ❌ prop drilling — intermediates don't use the prop\n<Page userId={userId}><Header userId={userId}><UserAvatar userId={userId} /></Header></Page>\n\n// ✅ composition — pass the component, not the data\n<Page><Header avatar={<UserAvatar userId={userId} />} /></Page>\n```",
      quickRules: "- ✅ 1-2 levels: fine\n- ✅ 3+ levels through components that don't use the prop: composition or context\n- ❌ passing through 5 components none of which use it: prop drilling",
      watchOut: "👀 **Watch out:** Context re-renders all consumers when value changes. For frequently-changing data, prop passing or local state may be more performant.",
      dryRun: "🔁 **Think:** ShipmentCard renders a record AND passes status to StatusBadge. Does ShipmentCard use status itself (for className, conditional rendering)? Is this prop drilling?",
      build: "**Learning focus:** Compose ShipmentCard with StatusBadge — understanding the boundary between legitimate prop passing and true prop drilling.",
    }
  },
  {
    id: "step3", type: "question", phase: "Step 3 of 5",
    paal: "Build ShipmentList that accepts a ShipmentRecord[] and renders a ShipmentCard for each with a key prop.",
    hint: "ShipmentList is a pure presenter — no filtering, no state, no event handling. Its single job: map data to cards.",
    example_code: "const OrderList = ({ orders }: { orders: OrderRecord[] }): JSX.Element => (\n  <div>{orders.map(o => <OrderCard key={o.orderId} order={o} />)}</div>\n);",
    think_prompt: "ShipmentList is a pure renderer. Should it accept a pre-filtered array or the full array plus a filter value?",
    mc_options: [
      "Accept full shipments array plus statusFilter — filter inside the component",
      "Accept a pre-filtered ShipmentRecord[] — filtering is the parent's responsibility",
      "Accept no props — fetch data internally",
    ],
    mc_correct_option: "Accept a pre-filtered ShipmentRecord[] — filtering is the parent's responsibility",
    mc_anchor: "ShipmentList's single responsibility is rendering. Filtering is data logic that belongs in the parent. If ShipmentList also filters, it mixes concerns and can't be used to render an unfiltered list without a special 'all' value.",
    why_this_matters: "Single responsibility makes components composable and testable. A ShipmentList that only renders can be tested with any array — no filter state needed. One that filters requires testing both concerns together.",
    answer_keywords: ["ShipmentListProps", "shipments", "ShipmentRecord[]", "ShipmentCard", "key", "shipmentId"],
    seed_code: "type ShipmentStatus = 'active' | 'delayed' | 'delivered';\ninterface ShipmentRecord { shipmentId: string; destination: string; status: ShipmentStatus; }\nconst StatusBadge = ({ status }: { status: ShipmentStatus }): JSX.Element => (<span className={`badge badge--${status}`}>{status}</span>);\nconst ShipmentCard = ({ shipment }: { shipment: ShipmentRecord }): JSX.Element => (<div className=\"card\"><p>{shipment.shipmentId}</p><p>{shipment.destination}</p><StatusBadge status={shipment.status} /></div>);",
    starter_code: "// ... (StatusBadge and ShipmentCard already defined above)\n\n// build ShipmentList here\n// props: shipments (ShipmentRecord[])\n// renders: a ShipmentCard per shipment with key",
    feedback_correct: "Exactly — ShipmentList is a pure presenter. Maps data to cards. No filtering, no state — just the rendering concern.",
    feedback_partial: "Close — make sure ShipmentList accepts a pre-filtered `shipments: ShipmentRecord[]` and uses `s.shipmentId` as the key.",
    feedback_wrong: "Define `interface ShipmentListProps { shipments: ShipmentRecord[]; }`. Map: `{shipments.map(s => <ShipmentCard key={s.shipmentId} shipment={s} />)}`.",
    expected: "interface ShipmentListProps {\n  shipments: ShipmentRecord[];\n}\n\nconst ShipmentList = ({ shipments }: ShipmentListProps): JSX.Element => (\n  <div className=\"shipment-list\">\n    {shipments.map(s => (\n      <ShipmentCard key={s.shipmentId} shipment={s} />\n    ))}\n  </div>\n);",
    analog_example: "const OrderList = ({ orders }: { orders: OrderRecord[] }): JSX.Element => (\n  <div>{orders.map(o => <OrderCard key={o.orderId} order={o} />)}</div>\n);",
    deepDiveLabel: "Pure presenter — but who handles the empty state?",
    deepDive: {
      hook: "ShipmentList maps the array. When empty, nothing renders. Should it handle its own empty state — or should the parent decide?",
      pain: "⚠️ **Lesson:** The empty state message — is it ShipmentList's responsibility or the parent's?",
      mentalModel: "Two approaches:\n1. **ShipmentList handles empty**: `if (shipments.length === 0) return <EmptyState />`  — self-contained, always renders something useful.\n2. **Parent handles empty**: Parent checks length before rendering ShipmentList.\n\nRight choice depends on reuse: same message everywhere → list owns it. Different messages per page → parent owns it.\n\nCommon pattern: ShipmentList handles generic empty. Parent can override with `emptyState?: React.ReactNode` prop.",
      discover: "```tsx\n// ✅ self-contained with optional override\ninterface ShipmentListProps {\n  shipments: ShipmentRecord[];\n  emptyState?: React.ReactNode;\n}\nconst ShipmentList = ({ shipments, emptyState }: ShipmentListProps) => {\n  if (shipments.length === 0) return <>{emptyState ?? <p>No shipments</p>}</>;\n  return <div>{shipments.map(...)}</div>;\n};\n```",
      quickRules: "- ✅ self-contained empty: always shows something\n- ✅ custom empty prop: flexible, parent controls message\n- ❌ no empty handling: blank space",
      watchOut: "👀 **Watch out:** An optional `emptyState?: React.ReactNode` prop is the named slot pattern from Lesson 7 applied to empty state.",
      dryRun: "🔁 **Think:** visible is `[]`. ShipmentList receives `shipments={[]}`. If no empty handling, what renders? If `if (shipments.length === 0) return <p>No shipments</p>`, what does the user see?",
      build: "**Learning focus:** Build ShipmentList as a pure presenter — understanding that empty state handling is a separate concern with multiple valid ownership models.",
    }
  },
  {
    id: "step4", type: "question", phase: "Step 4 of 5",
    paal: "Build DashboardShell that accepts a title string and children. Renders a page header and a main content area.",
    hint: "DashboardShell is a layout component — it provides structure but doesn't know what content it wraps. Use `children?: React.ReactNode` for the content slot.",
    example_code: "const PageShell = ({ title, children }: PageShellProps): JSX.Element => (\n  <div><header><h1>{title}</h1></header><main>{children}</main></div>\n);",
    think_prompt: "DashboardShell should be reusable across shipment, driver, and analytics dashboards. What does it need to know — and what should it be agnostic about?",
    mc_options: [
      "Accept shipments, filter state, and handle the list — fully self-contained",
      "Accept title and children — knows nothing about shipments",
      "Accept a render prop function for the content area",
    ],
    mc_correct_option: "Accept title and children — knows nothing about shipments",
    mc_anchor: "A layout shell that knows about shipments can only render shipment pages. A shell that accepts title and children can render any page. Layout agnosticism is what makes shells maximally reusable.",
    why_this_matters: "Layout shells are among the most reused components in enterprise apps. A shell that knows its content must be duplicated per page type. A shell accepting children is written once and used everywhere.",
    answer_keywords: ["DashboardShell", "title", "children", "React.ReactNode", "header", "main"],
    seed_code: "",
    starter_code: "// build DashboardShell here\n// props: title (string), children? (React.ReactNode)\n// renders: <div> with <header><h1>{title}</h1></header> and <main>{children}</main>",
    feedback_correct: "Exactly — DashboardShell knows about structure (header, main) and title. It knows nothing about shipments or content. That's what makes it a layout component.",
    feedback_partial: "Close — make sure children is typed as `React.ReactNode` and rendered inside the main element.",
    feedback_wrong: "Define `interface DashboardShellProps { title: string; children?: React.ReactNode; }`. Return `<div><header><h1>{title}</h1></header><main>{children}</main></div>`.",
    expected: "interface DashboardShellProps {\n  title: string;\n  children?: React.ReactNode;\n}\n\nconst DashboardShell = ({ title, children }: DashboardShellProps): JSX.Element => (\n  <div className=\"dashboard\">\n    <header className=\"dashboard__header\">\n      <h1>{title}</h1>\n    </header>\n    <main className=\"dashboard__content\">\n      {children}\n    </main>\n  </div>\n);",
    analog_example: "const AppLayout = ({ title, children }: AppLayoutProps): JSX.Element => (\n  <div><header><h1>{title}</h1></header><main>{children}</main></div>\n);",
    deepDiveLabel: "Layout shell with title and children — what about navigation, breadcrumbs, actions?",
    deepDive: {
      hook: "DashboardShell has title and children. The design team adds a breadcrumb trail and an 'actions' area in the header. You add them as props. Then a page doesn't need breadcrumbs. Another doesn't need actions. Props multiply.",
      pain: "⚠️ **Lesson:** As layout shells support more areas, props grow. What's the pattern for optional named slots?",
      mentalModel: "Named optional slots — all typed as `React.ReactNode`:\n```tsx\ninterface DashboardShellProps {\n  title: string;\n  children?: React.ReactNode;\n  breadcrumbs?: React.ReactNode;\n  actions?: React.ReactNode;\n}\n// Render slots conditionally:\n{breadcrumbs && <nav>{breadcrumbs}</nav>}\n{actions && <div className='actions'>{actions}</div>}\n```",
      discover: "```tsx\n// Usage:\n<DashboardShell\n  title='Shipments'\n  actions={<button>Add Shipment</button>}\n  breadcrumbs={<Breadcrumbs path={['Home', 'Shipments']} />}\n>\n  <ShipmentList />\n</DashboardShell>\n```",
      quickRules: "- ✅ optional ReactNode props for named layout slots\n- ✅ render slot only when provided: `{actions && <div>{actions}</div>}`\n- ❌ accepting typed data arrays in the layout — accept pre-rendered JSX, not data\n- start with children only, add named slots when there's a real recurring need",
      watchOut: "👀 **Watch out:** There's tension between flexibility (many slots) and simplicity (just children). Start simple, add slots for real needs.",
      dryRun: "🔁 **Think:** DashboardShell has `actions?: React.ReactNode`. A page renders it without actions. What does `{actions && <div>{actions}</div>}` render? Another page passes `actions={<button>Export</button>}`. What renders?",
      build: "**Learning focus:** Build a layout shell agnostic to its content — and understand optional named slots as the extensibility pattern.",
    }
  },
  {
    id: "step5", type: "question", phase: "Step 5 of 5",
    paal: "Compose the full shipment dashboard: DashboardShell wrapping ShipmentList, with filter state and derived visible list in the page component.",
    hint: "The page component owns state and filtering. DashboardShell provides structure. ShipmentList receives the pre-filtered visible array. Each component does exactly one thing.",
    example_code: "const OrderDashboard = (): JSX.Element => {\n  const [orders] = useState<OrderRecord[]>([...]);\n  const visible = orders.filter(o => o.status === 'active');\n  return (\n    <DashboardShell title=\"Orders\">\n      <OrderList orders={visible} />\n    </DashboardShell>\n  );\n};",
    think_prompt: "Map the responsibilities: who owns state, who filters, who renders the list, who provides the layout? Then write the hierarchy.",
    mc_options: [
      "One ShipmentDashboard that handles state, filtering, layout, and rendering",
      "ShipmentDashboardPage (state+filter) → DashboardShell (layout) → ShipmentList (render) → ShipmentCard (card) → StatusBadge (badge)",
      "DashboardShell handles everything — state, filter, and list",
    ],
    mc_correct_option: "ShipmentDashboardPage (state+filter) → DashboardShell (layout) → ShipmentList (render) → ShipmentCard (card) → StatusBadge (badge)",
    mc_anchor: "Each component has exactly one responsibility. The page owns state and filtering. The shell owns layout. The list owns rendering the array. The card owns rendering one record. The badge owns rendering one status. This hierarchy makes each piece independently testable and reusable.",
    why_this_matters: "This five-level hierarchy is the real-world pattern for enterprise dashboards. Changing the badge doesn't touch the list. Changing the layout doesn't touch the filter. A new page type reuses shell and badge but replaces the list. Composition at scale is what keeps large codebases maintainable.",
    answer_keywords: ["ShipmentDashboardPage", "useState", "visible", "DashboardShell", "ShipmentList", "shipments={visible}"],
    seed_code: "import { useState } from 'react';\ntype ShipmentStatus = 'active' | 'delayed' | 'delivered';\ninterface ShipmentRecord { shipmentId: string; destination: string; status: ShipmentStatus; }\nconst StatusBadge = ({ status }: { status: ShipmentStatus }): JSX.Element => (<span className={`badge badge--${status}`}>{status}</span>);\nconst ShipmentCard = ({ shipment }: { shipment: ShipmentRecord }): JSX.Element => (<div className=\"card\"><p>{shipment.shipmentId}</p><p>{shipment.destination}</p><StatusBadge status={shipment.status} /></div>);\nconst ShipmentList = ({ shipments }: { shipments: ShipmentRecord[] }): JSX.Element => (<div>{shipments.map(s => <ShipmentCard key={s.shipmentId} shipment={s} />)}</div>);\nconst DashboardShell = ({ title, children }: { title: string; children?: React.ReactNode }): JSX.Element => (<div><header><h1>{title}</h1></header><main>{children}</main></div>);",
    starter_code: "// (all components already defined above)\n\n// build ShipmentDashboardPage here\n// it owns: state (shipments), filter state, visible list derivation\n// it composes: DashboardShell → ShipmentList",
    feedback_correct: "Exactly — five components, five responsibilities, composed into one dashboard. The page owns state and filtering; every other component is a pure presenter.",
    feedback_partial: "Close — make sure state and filtering live in ShipmentDashboardPage (not inside DashboardShell or ShipmentList), and that ShipmentList receives the pre-filtered `visible` array.",
    feedback_wrong: "ShipmentDashboardPage: useState for shipments, derive visible, return `<DashboardShell title='Shipments Dashboard'><ShipmentList shipments={visible} /></DashboardShell>`.",
    expected: "const ShipmentDashboardPage = (): JSX.Element => {\n  const [shipments] = useState<ShipmentRecord[]>([\n    { shipmentId: 'NX-001', destination: 'Hamburg', status: 'active' },\n    { shipmentId: 'NX-002', destination: 'Rotterdam', status: 'delayed' },\n    { shipmentId: 'NX-003', destination: 'Antwerp', status: 'delivered' },\n  ]);\n  const [statusFilter, setStatusFilter] = useState<'all' | ShipmentStatus>('all');\n\n  const visible = statusFilter === 'all'\n    ? shipments\n    : shipments.filter(s => s.status === statusFilter);\n\n  return (\n    <DashboardShell title=\"Shipments Dashboard\">\n      <select value={statusFilter} onChange={e => setStatusFilter(e.target.value as 'all' | ShipmentStatus)}>\n        <option value=\"all\">All</option>\n        <option value=\"active\">Active</option>\n        <option value=\"delayed\">Delayed</option>\n        <option value=\"delivered\">Delivered</option>\n      </select>\n      <ShipmentList shipments={visible} />\n    </DashboardShell>\n  );\n};",
    analog_example: "const AnalyticsDashboard = (): JSX.Element => {\n  const [data] = useState<MetricRecord[]>([...]);\n  return (\n    <DashboardShell title=\"Analytics\">\n      <MetricList metrics={data} />\n    </DashboardShell>\n  );\n};",
    deepDiveLabel: "Five components composed — how do you decide when to split vs keep together?",
    deepDive: {
      hook: "A colleague says 'over-engineered — one ShipmentDashboard that does everything'. Another says 'split further — separate ShipmentCardHeader and ShipmentCardBody'. Who's right?",
      pain: "⚠️ **Lesson:** Component splitting has a cost (more files, indirection) and benefit (reusability, testability). What's the decision framework?",
      mentalModel: "**Split when**: component has more than one reason to change; part is reused elsewhere; part is independently testable with value; component is over ~100 lines and each section could stand alone.\n\n**Keep together when**: pieces only make sense together; splitting would create a component used in exactly one place with no independent test value; naming would be confusing ('ShipmentCardTitleText').",
      discover: "**Signals to split**: reuse, independent test value, multiple change reasons\n**Signals to keep**: single use, no independent test value, pieces are meaningless apart",
      quickRules: "- ✅ split: reusable, independently testable, multiple change reasons\n- ✅ keep: single use, no independent test value\n- ❌ split for small file size — indirection without value\n- ❌ keep a 500-line component because 'it all belongs together'\n- right size = one reason to change",
      watchOut: "👀 **Watch out:** Over-splitting creates abstraction debt — navigating many files to understand one component. Under-splitting creates monolith debt. Neither is free.",
      dryRun: "🔁 **Think:** Team adds a 'driver assigned' badge to ShipmentCard. Which components change — which don't? Adding WarehouseDashboard: which components can it reuse?",
      build: "**Learning focus:** Compose a five-component hierarchy with single responsibilities — understanding the split vs keep decision framework.",
    }
  },
];

const sideItems = [
  { label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" },
  { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" },
  { label: "Step 3", id: "step3" }, { label: "Step 4", id: "step4" },
  { label: "Step 5", id: "step5" },
];

export default createINPACTEngine({
  NODES, sideItems,
  lessonNum: 20,
  title: "Component Composition",
  shortName: "PATTERNS — COMPOSITION",
});
