import createINPACTEngine from "../inpact_engine_shared";

const NODES = [
  {
    id: "intro",
    type: "reveal",
    phase: "Lesson",
    content: {
      tag: "LESSON #6 (TypeScript)",
      title: "TypeScript — Type Guards",
      body: "A union type says a value could be one of several shapes — but TypeScript only narrows the union when you prove which shape you have. Type guards are those proofs: built-in checks like typeof and instanceof, the in operator for discriminated fields, and user-defined predicates that return x is SomeType. This lesson connects guards to real React patterns — handlers that accept unknown API payloads, discriminated union props, and safe filtering of mixed arrays.",
      usecase:
        "A webhook delivers JSON that might be a shipment update, a driver update, or a ping event. One handler receives unknown data, inspects a discriminant field, and routes to the right UI branch. Without type guards every branch would need manual casts — guards let TypeScript verify the control flow so refactors stay safe.",
    },
  },
  {
    id: "prereqs",
    type: "prereqs",
    phase: "Prerequisites",
    items: [
      {
        lesson: 1,
        label: "JSX — The Full Language",
        reason: "Guards often sit inside event handlers and conditional JSX. You need JSX and conditional rendering before combining guards with component output.",
      },
      {
        lesson: 2,
        label: "Inventory row — readonly fields, unions, nested types",
        reason: "You narrow to interface shapes — Lesson 2 is where structured props and records become familiar.",
      },
      {
        lesson: 5,
        label: "TypeScript — Enums",
        reason: "Discriminants are often enums or string literals. Lesson 5 covers named constant sets that appear in discriminated unions.",
      },
    ],
  },
  {
    id: "objectives",
    type: "objectives",
    phase: "Objectives",
    items: [
      "Use typeof and instanceof to narrow primitive and class-based values",
      "Use the in operator to narrow discriminated union types",
      "Write a user-defined type predicate (parameterName is SomeType)",
      "Explain how control-flow analysis applies type guards after a check",
      "Recognise when discriminated unions replace long chains of optional fields",
    ],
  },
  {
    id: "step1",
    type: "question",
    phase: "Step 1 of 5",
    paal: "Given `function logPayload(data: unknown)`, which check correctly narrows `data` to a string before calling `data.toUpperCase()`?",
    hint: "typeof returns a string union of runtime types — compare to 'string'.",
    example_code: `if (typeof value === 'number') { value.toFixed(2); }`,
    think_prompt: "unknown must be narrowed — which guard proves a primitive string?",
    mc_options: [
      "`if (data)` then call `data.toUpperCase()`",
      "`if (typeof data === 'string')` then call `data.toUpperCase()`",
      "`if (data as string)` then call `data.toUpperCase()`",
    ],
    mc_correct_option: "`if (typeof data === 'string')` then call `data.toUpperCase()`",
    mc_anchor:
      "Truthiness does not remove unknown — only typeof / comparison / custom predicates narrow unknown safely. Casts bypass checking.",
    why_this_matters:
      "API boundaries often start as unknown — typeof is the first line of defence before touching string methods.",
    answer_keywords: ["typeof", "string", "unknown"],
    seed_code: "",
    starter_code: "",
    feedback_correct: "Yes — typeof narrows unknown to string inside the block.",
    feedback_partial: "",
    feedback_wrong: "Use `if (typeof data === 'string') { data.toUpperCase(); }`.",
    expected: "`if (typeof data === 'string')` then call `data.toUpperCase()`",
    analog_example: "",
    deepDiveLabel: "unknown vs any",
    deepDive: {
      hook: "any disables checking; unknown forces you to narrow — prefer unknown at boundaries.",
      pain: "⚠️ Casting unknown to a shape without a runtime check revives any's problems.",
      mentalModel: "Treat unknown as a sealed box — open it only with guards.",
      discover: "```ts\nfunction safeLen(x: unknown) {\n  if (typeof x === 'string' || Array.isArray(x)) return x.length;\n}\n```",
      quickRules: "- ✅ typeof / Array.isArray / in / custom predicates\n- ❌ `as` without validation",
      watchOut: "",
      dryRun: "",
      build: "",
    },
  },
  {
    id: "step2",
    type: "question",
    phase: "Step 2 of 5",
    paal: "You have `type UiEvent = { kind: 'click'; x: number } | { kind: 'keydown'; key: string }`. Inside `function handle(e: UiEvent)`, which condition narrows to the keydown branch?",
    hint: "Compare the discriminant field kind to a literal — TypeScript narrows the union.",
    example_code: `if (msg.type === 'error') { console.log(msg.code); }`,
    think_prompt: "Discriminated unions carry a shared field whose literal type differs per variant.",
    mc_options: [
      "`if ('key' in e)`",
      "`if (e.kind === 'keydown')`",
      "`if (e.key)`",
    ],
    mc_correct_option: "`if (e.kind === 'keydown')`",
    mc_anchor:
      "`in` checks property existence, not discriminant equality. `e.key` might error on the click variant. Comparing `kind` to the literal narrows correctly.",
    why_this_matters:
      "Event payloads and Redux actions commonly use discriminated unions — comparing the discriminant is the idiomatic guard.",
    answer_keywords: ["kind", "keydown", "UiEvent"],
    seed_code: "",
    starter_code: "",
    feedback_correct: "Correct — literal comparison on the discriminant narrows the union.",
    feedback_partial: "",
    feedback_wrong: "Use `if (e.kind === 'keydown') { /* e.key is string here */ }`.",
    expected: "`if (e.kind === 'keydown')`",
    analog_example: "",
    deepDiveLabel: "in vs discriminant compare",
    deepDive: {
      hook: "`in` answers 'does this object have a property' — not 'which variant am I holding'.",
      pain: "⚠️ Using `in` on a union can narrow oddly if both variants share property names.",
      mentalModel: "Prefer a dedicated discriminant field with unique literals per variant.",
      discover: "```ts\ntype A = { t: 'a'; n: number };\ntype B = { t: 'b'; s: string };\nfunction f(x: A | B) { if (x.t === 'a') return x.n; return x.s; }\n```",
      quickRules: "- ✅ Compare discriminant to literal\n- ⚠️ `in` when shapes differ by presence",
      watchOut: "",
      dryRun: "",
      build: "",
    },
  },
  {
    id: "step3",
    type: "question",
    phase: "Step 3 of 5",
    paal: "Pick the valid user-defined type predicate signature for testing whether an unknown value is a number.",
    hint: "Return type `arg is number` tells TypeScript the relationship when the function returns true.",
    example_code: `function isNonEmptyString(v: unknown): v is string {\n  return typeof v === 'string' && v.length > 0;\n}`,
    think_prompt: "A type predicate lives in the return type position after the parameter list.",
    mc_options: [
      "`function isNumber(n: unknown): boolean`",
      "`function isNumber(n: unknown): n is number`",
      "`function isNumber(n: number): unknown`",
    ],
    mc_correct_option: "`function isNumber(n: unknown): n is number`",
    mc_anchor:
      "Boolean return types do not communicate narrowing. Predicate return `n is number` couples truthiness to the narrowed type.",
    why_this_matters:
      "Reusable predicates keep validation logic in one place and compose inside filter/map pipelines.",
    answer_keywords: ["is", "unknown", "number"],
    seed_code: "",
    starter_code: "",
    feedback_correct: "Exactly — `n is number` is the predicate form.",
    feedback_partial: "",
    feedback_wrong: "Use `function isNumber(n: unknown): n is number`.",
    expected: "`function isNumber(n: unknown): n is number`",
    analog_example: "",
    deepDiveLabel: "Predicates + filter",
    deepDive: {
      hook: "`array.filter(isNumber)` returns number[] when the callback is a predicate.",
      pain: "⚠️ Predicate must be a named function reference — inline arrows rarely infer as predicates.",
      mentalModel: "The type system trusts your boolean only when you promise `x is T`.",
      discover: "```ts\nconst nums = mixed.filter(isNumber);\n```",
      quickRules: "- ✅ export reusable predicates\n- ❌ lying predicates — runtime bugs",
      watchOut: "",
      dryRun: "",
      build: "",
    },
  },
  {
    id: "step4",
    type: "question",
    phase: "Step 4 of 5",
    paal: "After `if (typeof value === 'object' && value !== null && 'id' in value)` inside a function, what does TypeScript know about `value`?",
    hint: "in narrows to an object type that includes at least property id — not a specific interface unless combined further.",
    example_code: "",
    think_prompt: "in produces a structural narrowing — you still may need another check for the full shape.",
    mc_options: [
      "`value` is definitely a string",
      "`value` is `object & Record<'id', unknown>` (an object with an id key)",
      "`value` is `null`",
    ],
    mc_correct_option: "`value` is `object & Record<'id', unknown>` (an object with an id key)",
    mc_anchor:
      "typeof object excludes primitives except null edge case — you added `value !== null`. `in` adds that id exists; TypeScript still does not know id's value type without more checks.",
    why_this_matters:
      "Incremental guards mirror how you validate JSON — peel layers instead of one giant cast.",
    answer_keywords: ["in", "object", "id"],
    seed_code: "",
    starter_code: "",
    feedback_correct: "Right — this is structural narrowing, not a full domain type yet.",
    feedback_partial: "",
    feedback_wrong: "Choose the option describing an object with an id property.",
    expected: "`value` is `object & Record<'id', unknown>` (an object with an id key)",
    analog_example: "",
    deepDiveLabel: "Layered validation",
    deepDive: {
      hook: "Combine typeof, null checks, and in before reading specific fields.",
      pain: "⚠️ Optional chaining is not a substitute for narrowing unknown.",
      mentalModel: "Each guard adds facts the checker remembers in that branch.",
      discover: "Follow with discriminant compare or schema validation for full safety.",
      quickRules: "- ✅ small guards composed\n- ❌ one `as FullType`",
      watchOut: "",
      dryRun: "",
      build: "",
    },
  },
  {
    id: "step5",
    type: "question",
    phase: "Step 5 of 5",
    paal: "In `switch (event.kind)` handling every member of a union of literals, what do you put in the `default` branch to let TypeScript verify exhaustiveness?",
    hint: "Assign the narrowed remaining type to `never` — if any variant is missing, TypeScript errors.",
    example_code: `const _exhaustive: never = event;`,
    think_prompt: "never means 'should be unreachable' — leverage it after all cases.",
    mc_options: [
      "`return null`",
      "`const _check: never = event;`",
      "`console.log(event)`",
    ],
    mc_correct_option: "`const _check: never = event;`",
    mc_anchor:
      "If a new union member is added, the default branch becomes assignable to never and fails — forcing you to handle the new case.",
    why_this_matters:
      "Exhaustive switches are how teams keep domain event handling safe as enums grow.",
    answer_keywords: ["never", "default", "exhaustive"],
    seed_code: "",
    starter_code: "",
    feedback_correct: "Yes — the never assignment is the standard exhaustiveness pattern.",
    feedback_partial: "",
    feedback_wrong: "Use `const _check: never = event;` in default after all cases.",
    expected: "`const _check: never = event;`",
    analog_example: "",
    deepDiveLabel: "Exhaustiveness checking",
    deepDive: {
      hook: "Combine discriminated unions + switch + never default for compiler-backed coverage.",
      pain: "⚠️ Forgetting default lets cases fall through without errors.",
      mentalModel: "never is the empty type — nothing should inhabit it at the end of a full switch.",
      discover: "```ts\ntype Kind = 'a' | 'b';\nfunction f(k: Kind) {\n  switch (k) {\n    case 'a': return 1;\n    case 'b': return 2;\n    default: {\n      const _x: never = k;\n      return _x;\n    }\n  }\n}\n```",
      quickRules: "- ✅ default: never assign\n- ❌ silent fall-through",
      watchOut: "",
      dryRun: "",
      build: "",
    },
  },
];

const sideItems = [
  { label: "Lesson", id: "intro" },
  { label: "Objectives", id: "objectives" },
  { label: "Step 1", id: "step1" },
  { label: "Step 2", id: "step2" },
  { label: "Step 3", id: "step3" },
  { label: "Step 4", id: "step4" },
  { label: "Step 5", id: "step5" },
];

export default createINPACTEngine({
  NODES,
  sideItems,
  lessonNum: 6,
  title: "TypeScript — Type Guards",
  shortName: "TS — TYPE GUARDS",
});
