import createINPACTEngine from "../inpact_engine_shared";

export const JS_INTERVIEW_TITLES = [
  "Write a counter app with increment decrement reset",
  "Write a toggle visibility widget",
  "Write controlled input and live preview",
  "Write array deduplication in 3 different ways",
  "Write a function to flatten nested arrays",
  "Write a deep clone utility without libraries",
  "Write a function to merge objects deeply",
  "Write a function to chunk an array by size",
  "Write a function to group items by key",
  "Write a function to sort objects by multiple keys",
  "Write a balanced parentheses checker",
  "Write a palindrome checker ignoring punctuation and case",
  "Write an anagram checker",
  "Write a first non repeating character finder",
  "Write a frequency counter for words in a sentence",
  "Write a custom map polyfill",
  "Write a custom filter polyfill",
  "Write a custom reduce polyfill",
  "Write a custom bind polyfill",
  "Write a custom once function utility",
  "Build a todo list CRUD app in JavaScript",
  "Build a notes app with create edit delete and search",
  "Build a shopping cart quantity manager",
  "Build an accordion component",
  "Build tabs with keyboard navigation",
  "Build a modal with escape and backdrop close",
  "Build a dropdown with outside click close",
  "Build a tooltip with smart positioning",
  "Build a star rating component",
  "Build an image carousel with autoplay and pause",
  "Build a sortable and filterable table",
  "Build client side pagination for a list",
  "Build infinite scroll with intersection observer",
  "Build a typeahead autocomplete box",
  "Build a debounced search input",
  "Build drag and drop list reordering",
  "Build Kanban style card movement",
  "Build a multi step form with validation",
  "Build OTP input with auto focus behavior",
  "Build file upload preview and progress UI",
  "Write a debounce utility",
  "Write a throttle utility",
  "Write retry with exponential backoff",
  "Write request deduplication for identical fetches",
  "Write a timeout wrapper for promises",
  "Write Promise all from scratch",
  "Write Promise race from scratch",
  "Write a cancellable async task abstraction",
  "Write a queue that runs async tasks with concurrency limit",
  "Write polling with start stop and backoff",
  "Build a weather dashboard using public API",
  "Build GitHub user search with pagination",
  "Build product listing with sort filter search",
  "Build optimistic UI for add and delete actions",
  "Build stale while revalidate cache layer",
  "Build offline first notes with localStorage fallback",
  "Build undo and redo for text editor state",
  "Build command palette with fuzzy search",
  "Build keyboard shortcut manager",
  "Build global event bus pub sub",
  "Build mini router hash and history mode",
  "Build route guards for auth only pages",
  "Build lazy module loader for route chunks",
  "Build feature flag utility with variants",
  "Build memoization utility with cache size limit",
  "Build LRU cache class",
  "Build deep equality function",
  "Build object diff utility",
  "Build form state manager from scratch",
  "Build validation schema runner",
  "Build i18n translation helper with interpolation",
  "Build date range picker logic",
  "Build virtualized list rendering logic",
  "Build finite state machine for UI states",
  "Build wizard engine with conditional steps",
  "Build reusable notification and toast manager",
  "Build confirmation dialog service",
  "Build permissions utility can action subject",
  "Build breadcrumb generator from route tree",
  "Build client analytics tracker queue",
  "Build mini virtual DOM diff and patch",
  "Build tiny reactive store with subscriptions",
  "Build signal like primitive get set effect",
  "Build scheduler for priority based jobs",
  "Build race condition safe search UI",
  "Build memory leak detector for event listeners",
  "Build web worker integration for expensive calculations",
  "Build shared worker tab sync demo",
  "Build offline sync queue and replay",
  "Build websocket reconnect manager",
  "Build heartbeat and presence client logic",
  "Build CRDT lite collaborative text prototype",
  "Build sandboxed code runner safe eval strategy",
  "Build AST based code highlighter basics",
  "Build bundle size guard script",
  "Build long task profiler using performance API",
  "Build CLS FID LCP web vitals logger",
  "Build A B test assignment utility",
  "Build resilient checkout state recovery flow",
  "Build end to end capstone ecommerce frontend in vanilla JS",
];

export const TS_INTERVIEW_TITLES = [
  "Convert a JS counter app to strongly typed TS",
  "Type a todo CRUD app with strict models",
  "Type a form state object with field errors",
  "Write identity generic and explain inference",
  "Write pluck generic with keyof",
  "Write pick generic with keyof",
  "Write omit generic with keyof",
  "Write merge generic preserving key types",
  "Write typed groupBy helper",
  "Write typed sortBy helper",
  "Model API success error via discriminated unions",
  "Write exhaustive switch using never",
  "Type a reducer action union",
  "Type async state idle loading success error",
  "Type a permission matrix model",
  "Type safe enum like constants with as const",
  "Build branded types for IDs",
  "Build money currency branded type",
  "Build typed URL params parser",
  "Build typed query string serializer",
  "Build typed event emitter",
  "Build typed pub sub bus",
  "Build typed command bus",
  "Build typed middleware pipeline",
  "Build typed plugin system",
  "Build typed registry with key constraints",
  "Build typed dependency container",
  "Build typed cache interface",
  "Build typed localStorage wrapper",
  "Build typed sessionStorage wrapper",
  "Type React props for reusable button",
  "Type polymorphic React component props",
  "Type forwardRef component",
  "Type useRef for DOM and custom objects",
  "Type controlled input handlers",
  "Type form submit events",
  "Type context values and provider props",
  "Type reducer and dispatch for context store",
  "Type custom hook return tuples",
  "Type async hooks with generic result and error",
  "Build generic data table props API",
  "Build typed column definitions with renderers",
  "Build typed pagination hook",
  "Build typed filter and sort state model",
  "Build typed tree node structure",
  "Build typed graph adjacency model",
  "Build typed route config map",
  "Build typed nav schema and guards",
  "Build typed notification payloads",
  "Build typed modal manager API",
  "Implement DeepPartial type",
  "Implement DeepReadonly type",
  "Implement Mutable type",
  "Implement NonEmptyArray type",
  "Implement TupleToUnion type",
  "Implement UnionToIntersection type",
  "Implement ValueOf type",
  "Implement RequireAtLeastOne type",
  "Implement RequireOnlyOne type",
  "Implement KeysMatching type",
  "Build typed fetch client with endpoint map",
  "Build typed REST resource wrapper",
  "Build typed GraphQL result helpers",
  "Build typed query key factory",
  "Build typed optimistic update shape",
  "Build typed normalization for entities",
  "Build typed denormalization selector",
  "Build typed state machine transitions",
  "Build typed finite workflow graph",
  "Build typed feature flag variants",
  "Build template literal route params type",
  "Build type safe i18n key lookup",
  "Build type safe form schema builder",
  "Build schema to type mapper",
  "Build type guards for unknown API payloads",
  "Build runtime validator and inferred type bridge",
  "Build typed error hierarchy classes",
  "Build typed retry policy config",
  "Build typed backoff strategy interface",
  "Build typed task scheduler interface",
  "Build mini Result functional helpers",
  "Build Option helpers in TS",
  "Build typed parser combinator basics",
  "Build typed AST node union",
  "Build typed visitor pattern",
  "Build typed command history undo redo",
  "Build typed plugin hooks with lifecycle events",
  "Build typed form library core APIs",
  "Build typed design tokens model",
  "Build typed theme contract checker",
  "Build typed analytics event catalog",
  "Build typed A B experiment assignment model",
  "Build typed permissions DSL",
  "Build typed micro frontend contract",
  "Build typed shared UI package API",
  "Build typed OpenAPI client generator skeleton",
  "Build typed test utility factory",
  "Build typed mock data builders",
  "Build typed monorepo package boundary checks",
  "Build end to end capstone React plus TS enterprise dashboard",
];

export const NODE_INTERVIEW_TITLES = [
  "Build a health check endpoint",
  "Build todo CRUD REST API",
  "Build notes CRUD REST API",
  "Build user signup login endpoints",
  "Build JWT auth middleware",
  "Build refresh token rotation flow",
  "Build password reset flow",
  "Build role based access middleware",
  "Build permission based access middleware",
  "Build centralized error handler middleware",
  "Build request validation middleware",
  "Build rate limiter middleware",
  "Build request logging middleware",
  "Build correlation ID middleware",
  "Build CORS config by environment",
  "Build file upload endpoint with validation",
  "Build image resize endpoint pipeline",
  "Build secure static file serving rules",
  "Build pagination filter sort API pattern",
  "Build API response envelope standardizer",
  "Build product catalog API with search",
  "Build cart API with add remove update",
  "Build order placement API with validation",
  "Build inventory reservation API",
  "Build checkout API with idempotency keys",
  "Build webhook receiver with signature verification",
  "Build outbound webhook retry queue",
  "Build notification service API",
  "Build email queue worker endpoint trigger",
  "Build SMS provider failover wrapper",
  "Build BFF endpoint aggregating multiple services",
  "Build API gateway like proxy endpoint",
  "Build cache aside middleware with TTL",
  "Build stale while revalidate API cache",
  "Build Redis backed session store integration",
  "Build token revocation list in Redis",
  "Build optimistic concurrency control endpoint",
  "Build request deduplication layer",
  "Build bulk operation endpoint with partial failures",
  "Build CSV export endpoint with streaming",
  "Build SSE endpoint for live updates",
  "Build websocket server with rooms",
  "Build websocket auth handshake",
  "Build websocket reconnect strategy",
  "Build online presence tracker",
  "Build typing indicator protocol",
  "Build chat message delivery ack flow",
  "Build notification fan out service",
  "Build pub sub bridge for realtime events",
  "Build fallback long polling endpoint",
  "Build background job queue with retries",
  "Build dead letter queue handling",
  "Build cron scheduler for periodic tasks",
  "Build delayed job execution API",
  "Build job status tracking endpoint",
  "Build distributed lock for critical jobs",
  "Build graceful shutdown with in flight drain",
  "Build worker heartbeat lease mechanism",
  "Build duplicate job prevention logic",
  "Build backpressure aware producer controls",
  "Build OpenAPI documented REST service",
  "Build versioned APIs v1 and v2 with compatibility",
  "Build multi tenant context resolver middleware",
  "Build tenant level data isolation guards",
  "Build audit logging for all mutations",
  "Build soft delete and restore endpoints",
  "Build data retention cleanup task",
  "Build PII masking utility for logs",
  "Build secure secrets loading strategy",
  "Build feature flag evaluation endpoint",
  "Build tracing instrumentation for requests",
  "Build Prometheus metrics endpoint",
  "Build structured logging formatters",
  "Build slow query and slow route profiler hooks",
  "Build circuit breaker wrapper for external APIs",
  "Build fallback strategy for provider outages",
  "Build retry with jitter utility for upstream calls",
  "Build timeout and cancellation for HTTP clients",
  "Build load shedding middleware under pressure",
  "Build request queue and priority controls",
  "Build integration tests for auth flows",
  "Build contract tests for API responses",
  "Build end to end test harness for core routes",
  "Build test data factory and cleanup utilities",
  "Build mock server for third party dependencies",
  "Build chaos test for intermittent upstream failures",
  "Build benchmark script for hot endpoints",
  "Build memory leak detection test run",
  "Build security test cases for common OWASP attacks",
  "Build replay attack defenses for signed requests",
  "Build secure cookie session strategy",
  "Build CSRF protection flow for web clients",
  "Build API key management endpoints",
  "Build usage quota tracking and enforcement",
  "Build billing usage aggregation pipeline",
  "Build event sourced audit trail basics",
  "Build CQRS split read write endpoints basics",
  "Build blue green deploy readiness endpoint set",
  "Build disaster recovery simulation scripts",
  "Build end to end capstone production ready commerce backend Node",
];

function makeInterviewConfig(lessonNum, title, prefix, trackName) {
  const pad = String(lessonNum).padStart(2, "0");
  const shortName = `${prefix}${pad}`;
  const keywords = title
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((x) => x && x.length > 2)
    .slice(0, 6);

  const seedByTrack = {
    JSI: `// ${trackName} ${shortName}: ${title}
// Write your solution below.
`,
    TSI: `// ${trackName} ${shortName}: ${title}
// Add strict TypeScript types in your solution.
`,
    NDI: `// ${trackName} ${shortName}: ${title}
// Implement an endpoint/service design and core code.
`,
  };

  return {
    lessonNum,
    title,
    shortName,
    sideItems: [
      { label: "Lesson", id: "intro" },
      { label: "Objectives", id: "objectives" },
      { label: "Build", id: "build" },
    ],
    NODES: [
      {
        id: "intro",
        type: "reveal",
        phase: "Lesson",
        content: {
          tag: `${trackName} #${lessonNum}`,
          title,
          body: `Implement this interview task end-to-end.\n\nGoal: production-grade solution quality with clean code, edge-case handling, and clear reasoning.`,
          usecase:
            "This is a frequently asked interview pattern at frontend and fullstack teams.",
        },
      },
      {
        id: "objectives",
        type: "objectives",
        phase: "Objectives",
        items: [
          "Implement the core functionality requested by the prompt.",
          "Handle edge cases and invalid input gracefully.",
          "Write clean, readable code with sensible structure.",
          "Explain tradeoffs and complexity if asked.",
        ],
      },
      {
        id: "build",
        type: "question",
        phase: "Build",
        paal: `Solve: ${title}`,
        hint: `Start with a minimal correct implementation, then improve edge-case handling and readability.`,
        answer_keywords: keywords.length ? keywords : ["build", "solution"],
        seed_code: seedByTrack[prefix],
        feedback_correct:
          "Good work. Your solution appears complete and aligned to the task.",
        feedback_partial:
          "Close. Make sure your implementation fully satisfies the prompt and handles edge cases.",
        feedback_wrong:
          "Re-read the prompt and implement the core behavior first, then add robustness.",
        expected:
          "A complete, correct implementation for the prompt, including edge-case handling.",
      },
    ],
  };
}

export const JS_INTERVIEW_CURRICULUM = JS_INTERVIEW_TITLES.map((title, i) => ({
  title,
  shortName: `JSI${String(i + 1).padStart(2, "0")}`,
  why: "Common JavaScript coding interview lesson.",
}));

export const TS_INTERVIEW_CURRICULUM = TS_INTERVIEW_TITLES.map((title, i) => ({
  title,
  shortName: `TSI${String(i + 1).padStart(2, "0")}`,
  why: "Common TypeScript interview lesson with strong typing.",
}));

export const NODE_INTERVIEW_CURRICULUM = NODE_INTERVIEW_TITLES.map((title, i) => ({
  title,
  shortName: `NDI${String(i + 1).padStart(2, "0")}`,
  why: "Common Node.js interview lesson for API/backend depth.",
}));

const JS_INTERVIEW_CONFIGS = JS_INTERVIEW_TITLES.map((title, i) =>
  makeInterviewConfig(i + 1, title, "JSI", "JavaScript Interview")
);
const TS_INTERVIEW_CONFIGS = TS_INTERVIEW_TITLES.map((title, i) =>
  makeInterviewConfig(i + 1, title, "TSI", "TypeScript Interview")
);
const NODE_INTERVIEW_CONFIGS = NODE_INTERVIEW_TITLES.map((title, i) =>
  makeInterviewConfig(i + 1, title, "NDI", "Node Interview")
);

export const ENGINES_JS_INTERVIEW = JS_INTERVIEW_CONFIGS.map((c) =>
  createINPACTEngine(c)
);
export const ENGINES_TS_INTERVIEW = TS_INTERVIEW_CONFIGS.map((c) =>
  createINPACTEngine(c)
);
export const ENGINES_NODE_INTERVIEW = NODE_INTERVIEW_CONFIGS.map((c) =>
  createINPACTEngine(c)
);
