/**
 * Coding assist tags + task copy — must match write-smb-assist-engines.mjs
 * (assist tags there) and any live OneDev task tagged AssistModule: <tag>.
 *
 * Shared data, not a script: seed-smb-pipeline.mjs (fresh seed) and
 * patch-task-titles.mjs (patch existing live tasks in place) both import
 * this so title/story/ac copy only ever needs updating in one place.
 */
export const CODING_ASSISTS = {
  BookingDepositDesk: [
    {
      title: "Build the appointment list and booking form",
      assist: "idt-booking-appointment-list-form",
      focus: "frontend",
      story: "Client can request a slot",
      ac: "Upcoming appointments are listed on load; The form submits date, time, and service to request a slot; A confirmation state displays after a successful request.",
    },
    {
      title: "Build the appointments API with slot-conflict checks",
      assist: "idt-booking-appointments-api",
      focus: "backend",
      story: "Server owns availability",
      ac: "The API supports full CRUD for appointments; A request for an already-booked provider slot is rejected with a conflict; Appointments persist across requests.",
    },
    {
      title: "Build the deposit list and take-deposit form",
      assist: "idt-booking-deposit-list-form",
      focus: "frontend",
      story: "Money down protects the slot",
      ac: "Deposits are listed with client, amount, and linked appointment; The form validates the linked appointment before submitting; An empty state displays when no deposits exist.",
    },
    {
      title: "Build the deposits API with held/applied status",
      assist: "idt-booking-deposits-api",
      focus: "backend",
      story: "Deposit state is derived",
      ac: "The API rejects a deposit amount that is zero or negative; Deposit status is derived as held or applied, never trusted from the client; GET and POST responses both include the current status.",
    },
    {
      title: "Build a provider-filtered view of the day's appointments",
      assist: "idt-booking-day-board-filter",
      focus: "frontend",
      story: "Scan one stylist's day",
      ac: "The full appointment list is kept in state; The displayed list narrows to the selected provider; An empty message displays when no appointments match the filter.",
    },
  ],
  InvoiceFollowUpTracker: [
    {
      title: "Build the invoice list and create-invoice form",
      assist: "idt-invoice-list-form",
      focus: "frontend",
      story: "See what is owed",
      ac: "Invoices are listed with their current status; The form creates an invoice with client, amount, and due date; An empty state displays when no invoices exist.",
    },
    {
      title: "Build the invoices API with overdue status",
      assist: "idt-invoice-overdue-api",
      focus: "backend",
      story: "Server computes status",
      ac: "The API supports full CRUD for invoices; Overdue status is derived from the due date, not stored directly; A negative or zero amount is rejected.",
    },
    {
      title: "Build the reminder log and schedule-reminder form",
      assist: "idt-invoice-reminder-list-form",
      focus: "frontend",
      story: "Plan the nudge",
      ac: "Reminders are listed for review; The form schedules a reminder with invoice, channel, and send time; An empty state displays when no reminders exist.",
    },
    {
      title: "Build the reminders API preventing duplicate pending sends",
      assist: "idt-invoice-reminder-api",
      focus: "backend",
      tech: "http-api",
      story: "No spam doubles",
      ac: "A reminder can be scheduled per invoice and channel; Scheduling a second pending reminder for the same invoice and channel returns a conflict.",
    },
    {
      title: "Build an overdue-invoices view filtered by status",
      assist: "idt-invoice-overdue-board",
      focus: "frontend",
      story: "Chase what is late",
      ac: "The full invoice list is kept in state; The displayed list narrows to overdue invoices only; The underlying list is never mutated by the filter.",
    },
  ],
  LeadFollowUpInbox: [
    {
      title: "Build the lead inbox and capture form",
      assist: "idt-lead-list-form",
      focus: "frontend",
      story: "Catch the ask",
      ac: "Leads are listed as they come in; The form captures name, source, and note; An empty state displays when no leads exist.",
    },
    {
      title: "Build the leads API with fresh/stale status",
      assist: "idt-lead-stale-api",
      focus: "backend",
      story: "Stale is computed",
      ac: "The API supports full CRUD for leads; Stale status is derived from the captured date, never trusted from the client.",
    },
    {
      title: "Build the reply-notes list and add-note form",
      assist: "idt-lead-reply-list-form",
      focus: "frontend",
      story: "Log what we said",
      ac: "Notes are listed against their lead; The form adds a note with lead, body, and channel; An empty state displays when no notes exist.",
    },
    {
      title: "Build the lead-notes API blocking duplicate replies",
      assist: "idt-lead-notes-api",
      focus: "backend",
      tech: "http-api",
      story: "Timeline stays clean",
      ac: "A note can be added per lead; Adding an identical note body for the same lead returns a conflict.",
    },
    {
      title: "Build a stale-leads view filtered by status",
      assist: "idt-lead-stale-board",
      focus: "frontend",
      story: "Who needs a nudge",
      ac: "The full lead list is kept in state; The displayed list narrows to stale leads only; The underlying list is never mutated by the filter.",
    },
  ],
  ShiftCoverageBoard: [
    {
      title: "Build the shift board and publish-shift form",
      assist: "idt-shift-list-form",
      focus: "frontend",
      story: "Publish who works",
      ac: "Shifts are listed for the team; The form publishes a shift with worker, role, and start time; An empty state displays when no shifts exist.",
    },
    {
      title: "Build the shifts API rejecting double-booked workers",
      assist: "idt-shift-overlap-api",
      focus: "backend",
      story: "One body one place",
      ac: "A worker can be scheduled once per start time; Scheduling the same worker for the same start time returns a conflict.",
    },
    {
      title: "Build the open-coverage list and request-cover form",
      assist: "idt-coverage-list-form",
      focus: "frontend",
      story: "Ask for cover",
      ac: "Coverage requests are listed for the team; The form requests coverage with shift, reason, and needed-by date.",
    },
    {
      title: "Build the coverage API with open/filled status",
      assist: "idt-coverage-api",
      focus: "backend",
      story: "Filled is derived",
      ac: "Coverage status is derived from whether the request has been claimed, never trusted from the client; GET and POST responses both include the current status.",
    },
    {
      title: "Build an unfilled-coverage view filtered by status",
      assist: "idt-open-shift-board",
      focus: "frontend",
      story: "See what still needs cover",
      ac: "The full coverage list is kept in state; The displayed list narrows to unfilled requests only; The underlying list is never mutated by the filter.",
    },
  ],
  QuoteEstimateDesk: [
    {
      title: "Build the quote list and create-estimate form",
      assist: "idt-quote-list-form",
      focus: "frontend",
      story: "Send a price",
      ac: "Quotes are listed with client and total; The form creates a quote with client, total, and valid-until date; An empty state displays when no quotes exist.",
    },
    {
      title: "Build the quotes API with open/expired/accepted status",
      assist: "idt-quote-expiry-api",
      focus: "backend",
      tech: "crud",
      story: "Expiry is computed",
      ac: "Expired status is derived from the valid-until date; Accepted status is derived from a flag the server controls, never trusted from the client.",
    },
    {
      title: "Build the quote line-items list and add-line form",
      assist: "idt-quote-line-list-form",
      focus: "frontend",
      story: "Break down the price",
      ac: "Line items are listed against their quote; The form adds a line with quote, label, and amount; An empty state displays when no lines exist.",
    },
    {
      title: "Build the quote-lines API blocking duplicate labels",
      assist: "idt-quote-lines-api",
      focus: "backend",
      tech: "http-api",
      story: "No double Labor lines",
      ac: "A line label can be added once per quote; Adding a duplicate label for the same quote returns a conflict.",
    },
    {
      title: "Build an accepted-quotes view filtered by status",
      assist: "idt-quote-accepted-board",
      focus: "frontend",
      story: "See won work",
      ac: "The full quote list is kept in state; The displayed list narrows to accepted quotes only; The underlying list is never mutated by the filter.",
    },
  ],
  ReviewReplyInbox: [
    {
      title: "Build the review inbox and log-review form",
      assist: "idt-review-list-form",
      focus: "frontend",
      story: "Catch the feedback",
      ac: "Reviews are listed as they come in; The form logs a review with author, rating, and body; An empty state displays when no reviews exist.",
    },
    {
      title: "Build the reviews API with needs-reply status",
      assist: "idt-review-needs-reply-api",
      focus: "backend",
      tech: "crud",
      story: "Unanswered is derived",
      ac: "Needs-reply status is derived from whether a reply timestamp exists; The API validates the rating is within range.",
    },
    {
      title: "Build the review-replies list and write-reply form",
      assist: "idt-review-reply-list-form",
      focus: "frontend",
      story: "Answer on the record",
      ac: "Replies are listed against their review; The form writes a reply with review, body, and channel; An empty state displays when no replies exist.",
    },
    {
      title: "Build the review-replies API allowing one reply per channel",
      assist: "idt-review-replies-api",
      focus: "backend",
      tech: "http-api",
      story: "No double posts",
      ac: "A reply can be posted once per review and channel; Posting a second reply for the same review and channel returns a conflict.",
    },
    {
      title: "Build an unanswered-reviews view filtered by status",
      assist: "idt-review-unanswered-board",
      focus: "frontend",
      story: "Triage what still needs a reply",
      ac: "The full review list is kept in state; The displayed list narrows to reviews that still need a reply; The underlying list is never mutated by the filter.",
    },
  ],
  ClientReminderHub: [
    {
      title: "Build the reminder schedule list and create form",
      assist: "idt-reminder-schedule-list-form",
      focus: "frontend",
      story: "Plan the nudge",
      ac: "Reminders are listed for review; The form schedules a reminder with client, channel, and send time; An empty state displays when no reminders exist.",
    },
    {
      title: "Build the reminders API with due/sent status",
      assist: "idt-reminder-due-api",
      focus: "backend",
      tech: "crud",
      story: "Due is computed",
      ac: "Status is derived from send time and the sent flag as due, scheduled, or sent, never trusted from the client.",
    },
    {
      title: "Build the reminder-templates list and save-template form",
      assist: "idt-reminder-template-list-form",
      focus: "frontend",
      story: "Reuse the wording",
      ac: "Templates are listed for reuse; The form saves a template with name, body, and channel; An empty state displays when no templates exist.",
    },
    {
      title: "Build the reminder-templates API enforcing unique names",
      assist: "idt-reminder-templates-api",
      focus: "backend",
      tech: "http-api",
      story: "No duplicate names",
      ac: "A template name can be used once per channel; Saving a duplicate name for the same channel returns a conflict.",
    },
    {
      title: "Build a due-reminders view filtered by status",
      assist: "idt-reminder-due-board",
      focus: "frontend",
      story: "See what should send now",
      ac: "The full reminder schedule is kept in state; The displayed list narrows to reminders due now; The underlying list is never mutated by the filter.",
    },
  ],
  PackagePunchCard: [
    {
      title: "Build the package list and sell-package form",
      assist: "idt-package-list-form",
      focus: "frontend",
      story: "Sell prepaid visits",
      ac: "Packages are listed with client and service; The form sells a package with client, service, and total punches; An empty state displays when no packages exist.",
    },
    {
      title: "Build the packages API with remaining/empty status",
      assist: "idt-package-remaining-api",
      focus: "backend",
      tech: "crud",
      story: "Remaining is computed",
      ac: "Remaining balance is derived from used punches against total punches, never trusted from the client; Status reflects active or empty accordingly.",
    },
    {
      title: "Build the punch log and redeem-punch form",
      assist: "idt-punch-log-list-form",
      focus: "frontend",
      story: "Record a visit",
      ac: "Punches are listed against their package; The form redeems a punch with package, note, and time; An empty state displays when no punches exist.",
    },
    {
      title: "Build the punches API rejecting redeems on empty packages",
      assist: "idt-punch-redeem-api",
      focus: "backend",
      tech: "http-api",
      story: "No free punches",
      ac: "A punch can be redeemed only while the package has remaining balance; Redeeming an already-empty package returns a conflict.",
    },
    {
      title: "Build a low-balance view filtered by status",
      assist: "idt-package-low-board",
      focus: "frontend",
      story: "Upsell almost-empty cards",
      ac: "The full package list is kept in state; The displayed list narrows to packages running low; The underlying list is never mutated by the filter.",
    },
  ],
};
