export const REACT_TS_CURRICULUM = [
  { title: "First inventory screen — title + grocery card", prereqs: [] },
  { title: "Inventory row — readonly fields, unions, nested types", prereqs: [1] },
  { title: "Props + Interface", prereqs: [1,2] },
  { title: "Optional Props + Defaults", prereqs: [1,2,3] },
  { title: "children prop + ReactNode", prereqs: [1,2,3,4] },
  { title: "useState — Primitives", prereqs: [1] },
  { title: "useState — Objects + Spread", prereqs: [1,6] },
  { title: "useState — Arrays", prereqs: [1,6,7] },
  { title: "Controlled Inputs", prereqs: [1,6] },
  { title: "Controlled Select + Union Types", prereqs: [1,2,6,9] },
  { title: "Conditional Rendering", prereqs: [1,6] },
  { title: "List Rendering + key", prereqs: [1,6,7] },
  { title: "Event Handling — Click", prereqs: [1,6] },
  { title: "Event Handling — Input + Form", prereqs: [1,6,9] },
  { title: "Event Handling — Keyboard + Focus", prereqs: [1,6,9,14] },
  { title: "Component Composition", prereqs: [1,3,4,5] },
  { title: "Conditional CSS Classes", prereqs: [1,6,11] },
  { title: "Inventory Filter Bar (status + text + location)", prereqs: [1,6,9,10,11,13,14] },
  { title: "Derived Inventory Views (`inStock`, `low`, `expired`)", prereqs: [1,6,8,11,12,18] },
  { title: "Custom Hook — useInventoryFilters", prereqs: [18,19] },
  { title: "Custom Hook — useInventoryMutations", prereqs: [7,8,13,14,19] },
  { title: "Zustand — UI Workflow State (selected item, drawers, drafts)", prereqs: [16,20,21] },
  { title: "Redux Toolkit — Inventory Slice (domain state)", prereqs: [8,19,21,22] },
  { title: "RTK Async Inventory Flow (fetch/save/expire)", prereqs: [23] },
  { title: "Restaurant App Integration — roles, actions, and state sync", prereqs: [20,21,22,23,24] },
  { title: "AbortController", prereqs: [1,6,20,21,22,24] },
  { title: "useRef — DOM Access", prereqs: [1,6,20] },
  { title: "useRef — Mutable Values", prereqs: [1,6,20,26] },
  { title: "useReducer", prereqs: [1,6,7] },
  { title: "Custom Hook — Extract Logic", prereqs: [1,6,20,21] },
  { title: "Custom Hook — useFetch", prereqs: [1,6,20,21,24,29] },
  { title: "Custom Hook — useDebounce", prereqs: [1,6,20,21,29] },
  { title: "Custom Hook — useLocalStorage", prereqs: [1,6,20,29] },
  { title: "Custom Hook — useWindowSize", prereqs: [1,6,20,21,22,29] },
  { title: "Custom Hook — useClickOutside", prereqs: [1,6,20,21,26,29] },
  { title: "Custom Hook — useKeyPress", prereqs: [1,6,15,20,21,29] },
  { title: "Custom Hook — useOnlineStatus", prereqs: [1,6,20,21,29] },
  { title: "Custom Hook — useMediaQuery", prereqs: [1,6,20,21,22,29] },
  { title: "Custom Hook — useWebSocket", prereqs: [1,6,20,21,24,29] },
  { title: "Custom Hook — usePolling", prereqs: [1,6,20,21,24,29] },
  { title: "React.memo", prereqs: [1,3,4,6,16] },
  { title: "useMemo", prereqs: [1,6,20,40] },
  { title: "useCallback", prereqs: [1,6,20,40,41] },
  { title: "Identifying Re-renders", prereqs: [1,6,40,41,42] },
  { title: "List Virtualization — react-window", prereqs: [1,6,8,12,40] },
  { title: "Code Splitting + React.lazy", prereqs: [1,6,20] },
  { title: "Suspense + Fallback", prereqs: [1,6,45] },
  { title: "useTransition — React 18", prereqs: [1,6,20,41] },
  { title: "useDeferredValue — React 18", prereqs: [1,6,20,41,47] },
  { title: "Image Lazy Loading", prereqs: [1,6,26] },
  { title: "Skeleton Loading UI", prereqs: [1,4,22,47] },
  { title: "Dark Mode Toggle", prereqs: [1,4,52,53] },
  { title: "Context API — createContext + useContext", prereqs: [1,2,6,11] },
  { title: "Context — Theme Provider", prereqs: [1,2,6,52] },
  { title: "Context — Auth Provider", prereqs: [1,2,6,52,53] },
  { title: "Context Performance — Split + Memo", prereqs: [1,6,40,41,42,52] },
  { title: "Zustand — Store Basics", prereqs: [1,6,20] },
  { title: "Zustand — UI State", prereqs: [1,6,56] },
  { title: "Zustand — Persist Middleware", prereqs: [1,6,56,57] },
  { title: "Mini Redux from Scratch", prereqs: [1,6,28] },
  { title: "Redux Toolkit — createSlice", prereqs: [1,6,59] },
  { title: "Redux Toolkit — configureStore", prereqs: [1,6,60] },
  { title: "Redux Toolkit — useSelector + useDispatch", prereqs: [1,6,60,61] },
  { title: "RTK — createAsyncThunk", prereqs: [1,6,24,60,61,62] },
  { title: "RTK — Entity Adapter", prereqs: [1,6,60,61,62,63] },
  { title: "RTK Query — createApi", prereqs: [1,6,24,60] },
  { title: "RTK Query — useQuery", prereqs: [1,6,65] },
  { title: "RTK Query — useMutation", prereqs: [1,6,65,66] },
  { title: "RTK Query — WebSocket Listener", prereqs: [1,6,38,65,66] },
  { title: "TanStack Query — useQuery", prereqs: [1,6,24,29] },
  { title: "TanStack Query — useMutation", prereqs: [1,6,69] },
  { title: "TanStack Query — Infinite Scroll", prereqs: [1,6,69,70] },
  { title: "TanStack Query — Optimistic Updates", prereqs: [1,6,69,70,71] },
  { title: "WebSocket Real-time Updates", prereqs: [1,4,41,65] },
  { title: "Compound Components", prereqs: [1,2,3,4,5,52] },
  { title: "Render Props", prereqs: [1,2,3,4,76] },
  { title: "TypeScript — Generics in Components", prereqs: [1,2,137] },
  { title: "Generic Component — List<T>", prereqs: [1,2,3,8,76,137] },
  { title: "forwardRef", prereqs: [1,3,4,26] },
  { title: "useImperativeHandle", prereqs: [1,3,4,26,78] },
  { title: "Portal", prereqs: [1,6,20] },
  { title: "Error Boundary", prereqs: [1,3,4,6] },
  { title: "Recursive Component — TreeView", prereqs: [1,2,3,4,8] },
  { title: "HOC — withAuth", prereqs: [1,2,3,4,54] },
  { title: "HOC — withPermission", prereqs: [1,2,3,4,83] },
  { title: "Discriminated Union Props", prereqs: [1,2,3,4,11] },
  { title: "Slot Pattern", prereqs: [1,2,75,114,136] },
  { title: "Observer Pattern", prereqs: [1,4,18,27] },
  { title: "Polling vs WebSocket", prereqs: [1,4,41,42] },
  { title: "React Hook Form — Basics", prereqs: [1,3,4,6,9,14] },
  { title: "React Hook Form — Validation", prereqs: [1,3,4,89] },
  { title: "Zod — Schema Definition", prereqs: [1,2,137] },
  { title: "Dynamic Zod Schemas", prereqs: [1,2,93,94,137] },
  { title: "Zod + RHF — Integration", prereqs: [1,89,90,91] },
  { title: "Multi-Step Form — Wizard", prereqs: [1,6,11,89,90] },
  { title: "Conditional Form Fields", prereqs: [1,6,11,89,90] },
  { title: "Draft Autosave", prereqs: [1,6,20,21,31,89] },
  { title: "Form Array Fields", prereqs: [1,8,89,90] },
  { title: "File Upload Component", prereqs: [1,6,9,14,89] },
  { title: "Form State Persistence", prereqs: [1,4,35,90,91] },
  { title: "React Router — Setup + Basic Routes", prereqs: [1,6] },
  { title: "React Router — useNavigate + useParams", prereqs: [1,6,100] },
  { title: "React Router — Nested Routes + Outlet", prereqs: [1,6,100,101] },
  { title: "React Router — Lazy Routes", prereqs: [1,6,45,46,100] },
  { title: "Color Contrast in UI", prereqs: [1,4,16] },
  { title: "Protected Route — Auth Guard", prereqs: [1,6,54,100,101] },
  { title: "Protected Route — RBAC Guard", prereqs: [1,6,84,100,101,105] },
  { title: "JWT — Decode + Store", prereqs: [1,6,32] },
  { title: "Axios Interceptors — Token Attach", prereqs: [1,6,24,107] },
  { title: "Axios Interceptors — Token Refresh", prereqs: [1,6,24,107,108] },
  { title: "Session Timeout Hook", prereqs: [1,6,20,21,107] },
  { title: "Cookie-Based Auth Flow", prereqs: [1,6,107,108] },
  { title: "Multi-Tab Auth Sync", prereqs: [1,6,32,107,111] },
  { title: "OAuth2 PKCE Flow", prereqs: [1,6,107,108,109] },
  { title: "TypeScript — Enums", prereqs: [1,2] },
  { title: "RBAC — usePermission Hook", prereqs: [1,6,52,54,107] },
  { title: "Secure Token Rotation", prereqs: [1,6,107,108,109,113] },
  { title: "Optimistic UI", prereqs: [1,6,24,66,67,69] },
  { title: "Race Condition Fix", prereqs: [1,6,24,25,30] },
  { title: "Request Deduplication", prereqs: [1,6,24,30,65] },
  { title: "Pagination — Controlled", prereqs: [1,6,8,24,66] },
  { title: "Infinite Scroll — useIntersectionObserver", prereqs: [1,6,20,26,71] },
  { title: "CSV/Excel Export", prereqs: [1,6,8,13] },
  { title: "Clipboard API", prereqs: [1,6,13] },
  { title: "Date/Time Handling in UI", prereqs: [1,2,6] },
  { title: "Toast Notification System", prereqs: [1,6,52,80] },
  { title: "Modal — Portal + Focus Trap", prereqs: [1,6,15,80] },
  { title: "Accordion", prereqs: [1,6,11,13] },
  { title: "Tabs — Compound Component", prereqs: [1,6,11,74] },
  { title: "Drag and Drop — Reorder", prereqs: [1,6,8,13] },
  { title: "Debounced Search", prereqs: [1,6,9,31] },
  { title: "Star Rating Component", prereqs: [1,6,11,13] },
  { title: "Image Gallery + Lightbox", prereqs: [1,6,8,11,49] },
  { title: "Undo/Redo", prereqs: [1,6,8,28] },
  { title: "Conditional Classes — clsx", prereqs: [1,6,11,17] },
  { title: "Styled Component Pattern", prereqs: [1,3,6,18] },
  { title: "TypeScript — Type Guards", prereqs: [1,2,114] },
  { title: "TypeScript — Utility Types", prereqs: [1,2] },
  { title: "Controlled Select + Union Types (deep dive)", prereqs: [1,2,10,136,137] },
  { title: "Screen Reader Testing", prereqs: [1,4,114,128] },
  { title: "ARIA Roles + Labels", prereqs: [1,3,6] },
  { title: "Keyboard Navigation", prereqs: [1,6,15,140] },
  { title: "Focus Management", prereqs: [1,6,26,140,141] },
  { title: "useId — Stable IDs", prereqs: [1,6,20,140] },
  { title: "Testing — Render + Query", prereqs: [1,3,6] },
  { title: "Testing — User Interactions", prereqs: [1,6,13,144] },
  { title: "Testing — Async Components", prereqs: [1,6,24,144] },
  { title: "Testing — Context + Providers", prereqs: [1,6,52,144] },
  { title: "Testing — Custom Hooks", prereqs: [1,6,29,144] },
  { title: "Testing — Error Boundary", prereqs: [1,6,81,144] },
  { title: "Testing — Mocking Axios", prereqs: [1,6,24,108,144] },
  { title: "Testing — RTK Query", prereqs: [1,6,65,66,67,144] },
];

/** Grid / engine slot count (full roadmap). Bump with `REACT_TS_CURRICULUM` rows. */
export const REACT_TS_CURRICULUM_SLOT_COUNT = REACT_TS_CURRICULUM.length;

/**
 * Lessons you treat as learner-ready for hero copy (INPACT steps you have polished first).
 * The catalogue below may still list the full roadmap — update this as you ship.
 */
export const REACT_TS_GUIDED_LESSON_COUNT = 25;

export const LESSON_LIST = REACT_TS_CURRICULUM.map((l) => l.title);
export const LESSON_PREREQS = REACT_TS_CURRICULUM.map((l) => l.prereqs);

export function getLessonPrereqs(lessonNumber) {
  const idx = lessonNumber - 1;
  if (idx < 0 || idx >= LESSON_PREREQS.length) return [];
  return LESSON_PREREQS[idx];
}
