import createINPACTEngine from "../inpact_engine_shared";

export const NODES = [
  {
    id: "intro",
    type: "reveal",
    phase: "Lesson",
    content: {
      tag: "idt-quote-lines-api",
      title: "Quote lines API — no duplicate label on a quote",
      body: `Implement /api/quote-lines with persistence and a conflict rule:

  Store    →  in-memory array of QuoteLine
  Validate →  required fields before insert
  Conflict →  same quoteId + same label → conflict
  Routes   →  GET list, POST create (400 on bad/conflict)`,
      usecase: "Two Labor lines on one quote confuse totals. The API rejects duplicate labels.",
      designMock: {"kind":"api-sample","screenTitle":"/api/quote-lines","caption":"Sample requests/responses — the server owns the conflict rule.","getSample":"GET /api/quote-lines\n→ [ { \"id\": \"1\", \"quoteId\": \"q-1\", \"label\": \"Labor\", \"amount\": 900 } ]","postSample":"POST /api/quote-lines\n{ \"quoteId\": \"q-1\", \"label\": \"Labor\", \"amount\": 900 }\n→ 201 created  OR  409 conflict"},
    },
  },
  {
    id: "objectives",
    type: "objectives",
    phase: "Objectives",
    items: ["Keep an in-memory store and a helper that creates unique ids","Validate required fields before creating a record","Detect overlapping records so two bookings cannot claim the same slot","Implement GET to list records and POST to create with 400/409 errors"],
  },
  {
    id: "step1",
    type: "question",
    phase: "Step 1 of 4",
    paal: `Keep an in-memory store and a helper that creates unique ids

SAMPLE — /api/quote-lines
GET /api/quote-lines
→ [ { "id": "1", "quoteId": "q-1", "label": "Labor", "amount": 900 } ]

Every stored row needs a unique \`id\` generated by the server — it's never sent by the client, but every GET/POST sample above includes it.

Your task: declare \`let lines = []\` and a \`nextId()\` helper backed by a counter (not Date.now()).`,
    hint: `let lines = []; let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    example_code: `let guests = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    think_prompt: `\`\`\`text
SAMPLE — /api/quote-lines
GET /api/quote-lines
→ [ { "id": "1", "quoteId": "q-1", "label": "Labor", "amount": 900 } ]
\`\`\`

A server that must remember data across requests needs one place to keep it that persists between calls, plus a way to generate a new identifier every time a record is created. Where do the rows above live between one request and the next in a simple lesson server, and how does each new row get an id nothing else already has?`,
    mc_options: ["module-level array + a counter-based nextId helper","store only in the browser localStorage","ask the client to send the full database each time"],
    mc_correct_option: "module-level array + a counter-based nextId helper",
    mc_anchor: "module-level array + a counter-based nex",
    why_this_matters: `Two Labor lines on one quote confuse totals. The API rejects duplicate labels. APIs need a single place to read and write; an array plus a real id generator is enough for the lesson, and the same shape carries over once lines becomes a database table.`,
    answer_keywords: ["lines","nextId","nextIdCounter"],
    seed_code: `// store + ids
`,
    starter_code: `// store + ids
`,
    feedback_correct: "Correct — keep going.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Server owns the store.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `Two requests that arrive close together must never be handed the same id — a counter that only ever increases guarantees each new record gets a value nothing before it used, which a timestamp alone cannot promise.`,
    expected: `let lines = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return lines; }
`,
    analog_example: `let guests = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `An id generator only has one job: never repeat. A timestamp looks unique but isn't — two requests in the same millisecond produce the same value and silently overwrite each other's row. A counter that only increases is a small, boring fix for a bug that is otherwise invisible until real traffic hits it.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/quote-lines with persistence and a conflict rule:

  Store    →  in-memory array of QuoteLine
  Validate →  required fields before insert
  Conflict →  same quoteId + same label → conflict
  Routes   →  GET list, POST create (400 on bad/conflict)`,
      discover: `let lines = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return lines; }
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `let lines = []; let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    },
  },
  {
    id: "step2",
    type: "question",
    phase: "Step 2 of 4",
    paal: `Validate required fields before creating a record

SAMPLE — /api/quote-lines
POST /api/quote-lines
{ "quoteId": "q-1", "label": "Labor", "amount": 900 }

Your task: write validateLine(input) that returns an error string when a required field is missing/invalid, else null.`,
    hint: `validateLine(input) returns a string error or null.`,
    example_code: `if (!input?.name?.trim()) return "name is required";`,
    think_prompt: `\`\`\`text
SAMPLE — /api/quote-lines
POST /api/quote-lines
{ "quoteId": "q-1", "label": "Labor", "amount": 900 }
→ 201 created  OR  400 bad request
\`\`\`

Whatever a client sends in a request body can never be assumed well-formed — checking for missing or malformed fields before anything else runs is what keeps bad data from ever reaching storage. Looking at the POST body above, which checks have to pass before you push a row?`,
    mc_options: ["return an error string for missing/invalid fields, else null","always return null and trust the client","throw and crash the process on bad input"],
    mc_correct_option: "return an error string for missing/invalid fields, else null",
    mc_anchor: "return an error string for missing/inval",
    why_this_matters: `Bad payloads must fail early with a clear error — validation is how /api/quote-lines protects the store. Two Labor lines on one quote confuse totals. The API rejects duplicate labels.`,
    answer_keywords: ["validateLine","quoteId","label","amount"],
    seed_code: `let lines = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
`,
    starter_code: `let lines = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validateLine(input) {}
`,
    feedback_correct: "Correct — keep going.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Validate, then create.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `A validator is just a function that inspects the fields it was given and returns either a short error message or nothing at all — the caller decides what to do with that answer.`,
    expected: `let lines = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return lines; }
export function validateLine(input) {
  if (typeof input?.quoteId !== "string" || !input.quoteId.trim()) return "quoteId is required";
  if (typeof input?.label !== "string" || !input.label.trim()) return "label is required";
  if (typeof input?.amount !== "number" || input.amount <= 0) return "amount must be > 0";
  return null;
}
`,
    analog_example: `if (!input?.name?.trim()) return "name is required";`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `Validation that returns an error string (instead of throwing, or silently coercing) is what lets a route reply with a specific 400 message instead of crashing the process or quietly storing garbage. The check runs once, in one function, so every route into this resource gets the same guarantee.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/quote-lines with persistence and a conflict rule:

  Store    →  in-memory array of QuoteLine
  Validate →  required fields before insert
  Conflict →  same quoteId + same label → conflict
  Routes   →  GET list, POST create (400 on bad/conflict)`,
      discover: `let lines = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return lines; }
export function validateLine(input) {
  if (typeof input?.quoteId !== "string" || !input.quoteId.trim()) return "quoteId is required";
  if (typeof input?.label !== "string" || !input.label.trim()) return "label is required";
  if (typeof input?.amount !== "number" || input.amount <= 0) return "amount must be > 0";
  return null;
}
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `validateLine(input) returns a string error or null.`,
    },
  },
  {
    id: "step3",
    type: "question",
    phase: "Step 3 of 4",
    paal: `Detect overlapping records so two bookings cannot claim the same slot

SAMPLE — /api/quote-lines
Conflict rule: same quoteId + same label → conflict

Your task: write hasDuplicateLine(candidate) that returns true when an existing row already matches the conflict rule above.`,
    hint: `hasDuplicateLine(candidate) returns true when an existing row conflicts.`,
    example_code: `function seatTaken(seat, holds) {
  return holds.some((h) => h.seat === seat);
}`,
    think_prompt: `\`\`\`text
SAMPLE — /api/quote-lines
POST /api/quote-lines
→ 201 created  OR  409 conflict

Rule: same quoteId + same label → conflict
\`\`\`

Two requests can describe the same resource at the same moment — before inserting one, you compare it against everything already stored to decide whether it collides. Given the rule above, how should the server decide "conflict" before insert?`,
    mc_options: ["compare candidate against existing rows; true means conflict","always allow POST and fix conflicts in the UI later","delete the older row silently"],
    mc_correct_option: "compare candidate against existing rows; true means conflict",
    mc_anchor: "compare candidate against existing rows;",
    why_this_matters: `Clients can race — the server must refuse overlaps so the record stays trustworthy. Two Labor lines on one quote confuse totals. The API rejects duplicate labels.`,
    answer_keywords: ["hasDuplicateLine","some","quoteId"],
    seed_code: `let lines = [];
export function validateLine(input) { return null; }
`,
    starter_code: `let lines = [];
export function validateLine(input) { return null; }
export function hasDuplicateLine(candidate) {}
`,
    feedback_correct: "Correct — keep going.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Server detects conflict before insert.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `Checking one candidate record against a list of existing ones for a matching combination of fields is exactly what Array.prototype.some() is for — it stops at the first match and returns true or false.`,
    expected: `let lines = [];
export function validateLine(input) { return null; }
export function hasDuplicateLine(candidate) {
  return lines.some((row) => row.quoteId === candidate.quoteId && row.amount === candidate.amount);
}
`,
    analog_example: `function seatTaken(seat, holds) {
  return holds.some((h) => h.seat === seat);
}`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `Conflict detection is a search, not a special case: does any existing row match this candidate on the fields the business rule cares about? Once framed that way, "no double-booking a provider" and "no duplicate template name" are the same one-liner over different fields.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/quote-lines with persistence and a conflict rule:

  Store    →  in-memory array of QuoteLine
  Validate →  required fields before insert
  Conflict →  same quoteId + same label → conflict
  Routes   →  GET list, POST create (400 on bad/conflict)`,
      discover: `let lines = [];
export function validateLine(input) { return null; }
export function hasDuplicateLine(candidate) {
  return lines.some((row) => row.quoteId === candidate.quoteId && row.amount === candidate.amount);
}
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `hasDuplicateLine(candidate) returns true when an existing row conflicts.`,
    },
  },
  {
    id: "step4",
    type: "question",
    phase: "Step 4 of 4",
    paal: `Implement GET to list records and POST to create with 400/409 errors

SAMPLE — /api/quote-lines
GET → list  ·  POST → 201 / 400 / 409

Your task: wire list() to return lines, and create() to call validateLine (400 on error), then hasDuplicateLine (409 on conflict), then push and return 201.`,
    hint: `create: validate → overlap → push; list: res.json(lines)`,
    example_code: `if (seatTaken(body.seat, holds)) return res.status(409).json({ error: "taken" });`,
    think_prompt: `\`\`\`text
SAMPLE — /api/quote-lines
GET /api/quote-lines
→ [ ...rows ]

POST /api/quote-lines
→ 201 created  OR  400/409 error
\`\`\`

A route handler is where validation, conflict-checking, and storage come together — it should call the helpers you already wrote, in order, not re-implement any of their logic inline. How do GET and POST above use lines, validateLine, and hasDuplicateLine together?`,
    mc_options: ["GET lists store; POST validates, rejects conflict, else 201","POST always 201 even on overlap","GET returns HTML instead of JSON"],
    mc_correct_option: "GET lists store; POST validates, rejects conflict, else 201",
    mc_anchor: "GET lists store; POST validates, rejects",
    why_this_matters: `GET returns the store; POST validates (400), checks conflict (409), then inserts (201) — keep rules in helpers, not duplicated in the route. Two Labor lines on one quote confuse totals. The API rejects duplicate labels.`,
    answer_keywords: ["409","400","201","validateLine","hasDuplicateLine"],
    seed_code: `let lines = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validateLine(input) { return null; }
export function hasDuplicateLine(c) { return false; }
`,
    starter_code: `let lines = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validateLine(input) { return null; }
export function hasDuplicateLine(c) { return false; }
export function createHandlers() {
  return { list() {}, create() {} };
}
`,
    feedback_correct: "Correct — list and create with validation and conflict.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Wire helpers into GET/POST with the right status codes.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `A route handler's job is to call helpers in the right order and translate their answers into HTTP status codes — the actual rules already live in the functions written in earlier steps.`,
    expected: `let lines = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validateLine(input) { return null; }
export function hasDuplicateLine(candidate) {
  return lines.some((row) => row.quoteId === candidate.quoteId && row.amount === candidate.amount);
}
export function createHandlers() {
  return {
    list(_req, res) {
      res.json(lines);
    },
    create(req, res) {
      const err = validateLine(req.body);
      if (err) return res.status(400).json({ error: err });
      if (hasDuplicateLine(req.body)) return res.status(409).json({ error: "conflict" });
      const row = { id: nextId(), quoteId: req.body.quoteId, label: req.body.label, amount: req.body.amount };
      lines.push(row);
      res.status(201).json(row);
    },
  };
}
`,
    analog_example: `if (seatTaken(body.seat, holds)) return res.status(409).json({ error: "taken" });`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `Keeping validate/overlap/store as separate, named functions — instead of inlining their logic into the route — is what makes a route handler stay readable as a short sequence of checks: 400 if invalid, 409 if conflicting, 201 otherwise. The same three helpers can be unit-tested without ever touching HTTP.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/quote-lines with persistence and a conflict rule:

  Store    →  in-memory array of QuoteLine
  Validate →  required fields before insert
  Conflict →  same quoteId + same label → conflict
  Routes   →  GET list, POST create (400 on bad/conflict)`,
      discover: `let lines = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validateLine(input) { return null; }
export function hasDuplicateLine(candidate) {
  return lines.some((row) => row.quoteId === candidate.quoteId && row.amount === candidate.amount);
}
export function createHandlers() {
  return {
    list(_req, res) {
      res.json(lines);
    },
    create(req, res) {
      const err = validateLine(req.body);
      if (err) return res.status(400).json({ error: err });
      if (hasDuplicateLine(req.body)) return res.status(409).json({ error: "conflict" });
      const row = { id: nextId(), quoteId: req.body.quoteId, label: req.body.label, amount: req.body.amount };
      lines.push(row);
      res.status(201).json(row);
    },
  };
}
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `create: validate → overlap → push; list: res.json(lines)`,
    },
  },
];

const sideItems = [
  { label: "Lesson", id: "intro" },
  { label: "Objectives", id: "objectives" },
  { label: "Step 1", id: "step1" },
  { label: "Step 2", id: "step2" },
  { label: "Step 3", id: "step3" },
  { label: "Step 4", id: "step4" },
];

export default createINPACTEngine({
  NODES,
  sideItems,
  lessonNum: 0,
  title: "Quote lines API — no duplicate label on a quote",
  shortName: "Lines API",
});
