import createINPACTEngine from "../inpact_engine_shared";

export const NODES = [
  {
    id: "intro",
    type: "reveal",
    phase: "Lesson",
    content: {
      tag: "idt-package-remaining-api",
      title: "Packages API with remaining / empty status",
      body: `Implement /api/packages with a derived status:

  Store    →  in-memory ServicePackage rows
  Validate →  required fields
  Derive   →  used >= total → empty; else active (expose remaining)
  Routes   →  GET/POST attach computed status (do not trust client status)`,
      usecase: "Remaining punches must be computed from totals — clients cannot invent free punches.",
      designMock: {"kind":"api-sample","screenTitle":"/api/packages","caption":"Status is computed on the way out — clients cannot fake it.","getSample":"GET /api/packages\n→ [ { \"id\": \"1\", \"status\": \"…\" } ]","postSample":"POST /api/packages\n{ …fields… }\n→ 201 { …row, \"status\": \"…\" }"},
    },
  },
  {
    id: "objectives",
    type: "objectives",
    phase: "Objectives",
    items: ["Keep an in-memory store and a helper that creates unique ids","Validate required fields before creating a record","Derive a status from stored data instead of trusting the request body","Implement GET to list records and POST to create, attaching the derived status"],
  },
  {
    id: "step1",
    type: "question",
    phase: "Step 1 of 4",
    paal: `Keep an in-memory store and a helper that creates unique ids

SAMPLE — /api/packages
GET /api/packages
→ [ { "id": "1", "status": "…" } ]

Every stored row needs a unique \`id\` generated by the server — never sent by the client, but present on every row above.

Your task: declare \`let packages = []\` and a \`nextId()\` helper backed by a counter (not Date.now()).`,
    hint: `let packages = []; let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    example_code: `let tasks = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    think_prompt: `\`\`\`text
SAMPLE — /api/packages
GET /api/packages
→ [ { "id": "1", "status": "…" } ]
\`\`\`

A server that must remember data across requests needs one place to keep it that persists between calls, plus a way to generate a new identifier every time a record is created. Where do the rows above live between one request and the next, and how does each new row get an id nothing else already has?`,
    mc_options: ["module-level array + a counter-based nextId","no store — recompute from logs only","client sends the whole catalog every GET"],
    mc_correct_option: "module-level array + a counter-based nextId",
    mc_anchor: "module-level array + a counter-based nex",
    why_this_matters: `Remaining punches must be computed from totals — clients cannot invent free punches. One store is the single source of truth for list and create — every ServicePackage row created through /api/packages has to still be there on the next GET, or the desk would be lying about what's actually owed, booked, or open.`,
    answer_keywords: ["packages","nextId","nextIdCounter"],
    seed_code: `// store
`,
    starter_code: `// store
`,
    feedback_correct: "Correct — keep going.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Server owns the array.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `Two requests that arrive close together must never be handed the same id — a counter that only ever increases guarantees each new record gets a value nothing before it used, which a timestamp alone cannot promise.`,
    expected: `let packages = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return packages; }
`,
    analog_example: `let tasks = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `An id generator only has one job: never repeat. A timestamp looks unique but isn't — two requests in the same millisecond produce the same value and silently overwrite each other's row. A counter that only increases is a small, boring fix for a bug that is otherwise invisible until real traffic hits it.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/packages with a derived status:

  Store    →  in-memory ServicePackage rows
  Validate →  required fields
  Derive   →  used >= total → empty; else active (expose remaining)
  Routes   →  GET/POST attach computed status (do not trust client status)`,
      discover: `let packages = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return packages; }
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `let packages = []; let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    },
  },
  {
    id: "step2",
    type: "question",
    phase: "Step 2 of 4",
    paal: `Validate required fields before creating a record

SAMPLE — /api/packages
POST /api/packages
{ …fields… }

Your task: write validatePackage(input) that returns an error string when a required field is missing/invalid, else null.`,
    hint: `validatePackage returns error string or null.`,
    example_code: `if (!input?.title?.trim()) return "title is required";`,
    think_prompt: `\`\`\`text
SAMPLE — /api/packages
POST /api/packages
{ …fields… }
→ 201 created  OR  400 bad request
\`\`\`

Whatever a client sends in a request body can never be assumed well-formed — checking for missing or malformed fields before anything else runs is what keeps bad data from ever reaching storage. What must be true about the fields above before you insert a row?`,
    mc_options: ["error string for bad fields, else null","accept any JSON","coerce everything to strings silently"],
    mc_correct_option: "error string for bad fields, else null",
    mc_anchor: "error string for bad fields, else null",
    why_this_matters: `Validation keeps junk out of the store before status is ever derived from it. Remaining punches must be computed from totals — clients cannot invent free punches.`,
    answer_keywords: ["validatePackage","client","service","totalPunches","usedPunches"],
    seed_code: `let packages = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
`,
    starter_code: `let packages = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validatePackage(input) {}
`,
    feedback_correct: "Correct — keep going.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Validate first.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `A validator is just a function that inspects the fields it was given and returns either a short error message or nothing at all — the caller decides what to do with that answer.`,
    expected: `let packages = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return packages; }
export function validatePackage(input) {
  if (typeof input?.client !== "string" || !input.client.trim()) return "client is required";
  if (typeof input?.service !== "string" || !input.service.trim()) return "service is required";
  if (typeof input?.totalPunches !== "number" || input.totalPunches <= 0) return "totalPunches must be > 0";
  if (typeof input?.usedPunches !== "number" || input.usedPunches < 0) return "usedPunches must be >= 0";
  return null;
}
`,
    analog_example: `if (!input?.title?.trim()) return "title is required";`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `Validation that returns an error string (instead of throwing, or silently coercing) is what lets a route reply with a specific 400 message instead of crashing or quietly storing garbage. Run it once, in one function, so every route into this resource gets the same guarantee.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/packages with a derived status:

  Store    →  in-memory ServicePackage rows
  Validate →  required fields
  Derive   →  used >= total → empty; else active (expose remaining)
  Routes   →  GET/POST attach computed status (do not trust client status)`,
      discover: `let packages = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return packages; }
export function validatePackage(input) {
  if (typeof input?.client !== "string" || !input.client.trim()) return "client is required";
  if (typeof input?.service !== "string" || !input.service.trim()) return "service is required";
  if (typeof input?.totalPunches !== "number" || input.totalPunches <= 0) return "totalPunches must be > 0";
  if (typeof input?.usedPunches !== "number" || input.usedPunches < 0) return "usedPunches must be >= 0";
  return null;
}
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `validatePackage returns error string or null.`,
    },
  },
  {
    id: "step3",
    type: "question",
    phase: "Step 3 of 4",
    paal: `Derive a status from stored data instead of trusting the request body

SAMPLE — /api/packages
Rule: used >= total → empty; else active (expose remaining)

Your task: write derivePackageStatus(row, now) that returns the status string computed from the rule above — never from req.body.`,
    hint: `derivePackageStatus(row, now) returns the status string.`,
    example_code: `function taskStatus(item, today) {
  if (item.done) return "done";
  if (new Date(item.due) < today) return "late";
  return "open";
}`,
    think_prompt: `\`\`\`text
SAMPLE — /api/packages
GET /api/packages
→ [ { "id": "1", "status": "…" } ]

Rule: used >= total → empty; else active (expose remaining)
\`\`\`

A status label describing a record can always be recalculated from that record's own stored facts — comparing dates, or checking a boolean flag — rather than being sent by the client and simply trusted. Given the rule above, should the browser send status, or should the server compute it — and from what?`,
    mc_options: ["server derives status from stored facts; ignore client status","save req.body.status as-is","randomize status on every GET"],
    mc_correct_option: "server derives status from stored facts; ignore client status",
    mc_anchor: "server derives status from stored facts;",
    why_this_matters: `The browser can send anything; computing status from facts you already trust is what keeps it from being faked. Remaining punches must be computed from totals — clients cannot invent free punches.`,
    answer_keywords: ["derivePackageStatus"],
    seed_code: `let packages = [];
export function validatePackage(input) { return null; }
`,
    starter_code: `let packages = [];
export function validatePackage(input) { return null; }
export function derivePackageStatus(row, now = new Date()) {}
`,
    feedback_correct: "Correct — keep going.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Status is computed on the server.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `A derive function takes one stored row (plus, optionally, the current time) and returns a label computed purely from that row's own fields — it never reads anything the client sent in the current request.`,
    expected: `let packages = [];
export function validatePackage(input) { return null; }
export function derivePackageStatus(row) {
  if ((row.usedPunches || 0) >= row.totalPunches) return "empty";
  return "active";
}
`,
    analog_example: `function taskStatus(item, today) {
  if (item.done) return "done";
  if (new Date(item.due) < today) return "late";
  return "open";
}`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `A derived field only stays honest if it is recomputed from source facts every single time it's read, not stored and trusted. The moment a status is written once and reused, it can drift from the facts that produced it — a client-sent status has that problem from the very first request.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/packages with a derived status:

  Store    →  in-memory ServicePackage rows
  Validate →  required fields
  Derive   →  used >= total → empty; else active (expose remaining)
  Routes   →  GET/POST attach computed status (do not trust client status)`,
      discover: `let packages = [];
export function validatePackage(input) { return null; }
export function derivePackageStatus(row) {
  if ((row.usedPunches || 0) >= row.totalPunches) return "empty";
  return "active";
}
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `derivePackageStatus(row, now) returns the status string.`,
    },
  },
  {
    id: "step4",
    type: "question",
    phase: "Step 4 of 4",
    paal: `Implement GET to list records and POST to create, attaching the derived status

SAMPLE — /api/packages
GET → rows + status  ·  POST → 201 + status

Your task: wire list() to map derivePackageStatus over packages, and create() to validate, push, then return the row with derivePackageStatus attached.`,
    hint: `list: packages.map(r => ({...r, status: derivePackageStatus(r)}))`,
    example_code: `res.json(tasks.map((t) => ({ ...t, status: taskStatus(t) })));`,
    think_prompt: `\`\`\`text
SAMPLE — /api/packages
GET /api/packages
→ [ …rows with status ]

POST /api/packages
→ 201 { …row, "status": "…" }
\`\`\`

Attaching a computed field to data on its way out of a route means running the derive function once per record, every time that record is returned — never once at write time and then reused. How do GET and POST above reuse validatePackage and derivePackageStatus to guarantee status is never stale?`,
    mc_options: ["GET/POST attach derived status; POST validates first","POST stores client status verbatim","GET omits status"],
    mc_correct_option: "GET/POST attach derived status; POST validates first",
    mc_anchor: "GET/POST attach derived status; POST val",
    why_this_matters: `Always attach derive on the way out — POST validates, inserts, then attaches status, exactly like GET does. Remaining punches must be computed from totals — clients cannot invent free punches.`,
    answer_keywords: ["derivePackageStatus","validatePackage","201"],
    seed_code: `let packages = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validatePackage(input) { return null; }
export function derivePackageStatus(row, now = new Date()) { return "open"; }
`,
    starter_code: `let packages = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validatePackage(input) { return null; }
export function derivePackageStatus(row, now = new Date()) { return "open"; }
export function createHandlers() {
  return { list() {}, create() {} };
}
`,
    feedback_correct: "Correct — list and create attach derived status.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Always derive on the way out.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `A route handler's job is to call helpers in the right order and translate their answers into HTTP responses — validate first, then map the derive function over whatever gets returned.`,
    expected: `let packages = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validatePackage(input) { return null; }
export function derivePackageStatus(row, now = new Date()) { return "open"; }
export function createHandlers() {
  return {
    list(_req, res) {
      res.json(packages.map((r) => ({ ...r, status: derivePackageStatus(r) })));
    },
    create(req, res) {
      const err = validatePackage(req.body);
      if (err) return res.status(400).json({ error: err });
      const row = { id: nextId(), client: req.body.client, service: req.body.service, totalPunches: req.body.totalPunches, usedPunches: req.body.usedPunches, usedPunches: 0 };
      packages.push(row);
      res.status(201).json({ ...row, status: derivePackageStatus(row) });
    },
  };
}
`,
    analog_example: `res.json(tasks.map((t) => ({ ...t, status: taskStatus(t) })));`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `The rule "always derive on the way out" means the same map-over-derive call appears in both GET and POST — there is no separate code path where status could accidentally be skipped or hard-coded. Consistency here is what keeps the API honest under every route that touches this resource.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/packages with a derived status:

  Store    →  in-memory ServicePackage rows
  Validate →  required fields
  Derive   →  used >= total → empty; else active (expose remaining)
  Routes   →  GET/POST attach computed status (do not trust client status)`,
      discover: `let packages = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validatePackage(input) { return null; }
export function derivePackageStatus(row, now = new Date()) { return "open"; }
export function createHandlers() {
  return {
    list(_req, res) {
      res.json(packages.map((r) => ({ ...r, status: derivePackageStatus(r) })));
    },
    create(req, res) {
      const err = validatePackage(req.body);
      if (err) return res.status(400).json({ error: err });
      const row = { id: nextId(), client: req.body.client, service: req.body.service, totalPunches: req.body.totalPunches, usedPunches: req.body.usedPunches, usedPunches: 0 };
      packages.push(row);
      res.status(201).json({ ...row, status: derivePackageStatus(row) });
    },
  };
}
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `list: packages.map(r => ({...r, status: derivePackageStatus(r)}))`,
    },
  },
];

const sideItems = [
  { label: "Lesson", id: "intro" },
  { label: "Objectives", id: "objectives" },
  { label: "Step 1", id: "step1" },
  { label: "Step 2", id: "step2" },
  { label: "Step 3", id: "step3" },
  { label: "Step 4", id: "step4" },
];

export default createINPACTEngine({
  NODES,
  sideItems,
  lessonNum: 0,
  title: "Packages API with remaining / empty status",
  shortName: "Package API",
});
