import createINPACTEngine from "../inpact_engine_shared";

export const NODES = [
  {
    id: "intro",
    type: "reveal",
    phase: "Lesson",
    content: {
      tag: "idt-review-needs-reply-api",
      title: "Reviews API with needs-reply status",
      body: `Implement /api/reviews with a derived status:

  Store    →  in-memory Review rows
  Validate →  required fields
  Derive   →  if replied true → answered; else needs-reply
  Routes   →  GET/POST attach computed status (do not trust client status)`,
      usecase: "Needs-reply must come from whether a reply exists — not from a client-sent flag.",
      designMock: {"kind":"api-sample","screenTitle":"/api/reviews","caption":"Status is computed on the way out — clients cannot fake it.","getSample":"GET /api/reviews\n→ [ { \"id\": \"1\", \"status\": \"…\" } ]","postSample":"POST /api/reviews\n{ …fields… }\n→ 201 { …row, \"status\": \"…\" }"},
    },
  },
  {
    id: "objectives",
    type: "objectives",
    phase: "Objectives",
    items: ["Keep an in-memory store and a helper that creates unique ids","Validate required fields before creating a record","Derive a status from stored data instead of trusting the request body","Implement GET to list records and POST to create, attaching the derived status"],
  },
  {
    id: "step1",
    type: "question",
    phase: "Step 1 of 4",
    paal: `Keep an in-memory store and a helper that creates unique ids

SAMPLE — /api/reviews
GET /api/reviews
→ [ { "id": "1", "status": "…" } ]

Every stored row needs a unique \`id\` generated by the server — never sent by the client, but present on every row above.

Your task: declare \`let reviews = []\` and a \`nextId()\` helper backed by a counter (not Date.now()).`,
    hint: `let reviews = []; let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    example_code: `let tasks = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    think_prompt: `\`\`\`text
SAMPLE — /api/reviews
GET /api/reviews
→ [ { "id": "1", "status": "…" } ]
\`\`\`

A server that must remember data across requests needs one place to keep it that persists between calls, plus a way to generate a new identifier every time a record is created. Where do the rows above live between one request and the next, and how does each new row get an id nothing else already has?`,
    mc_options: ["module-level array + a counter-based nextId","no store — recompute from logs only","client sends the whole catalog every GET"],
    mc_correct_option: "module-level array + a counter-based nextId",
    mc_anchor: "module-level array + a counter-based nex",
    why_this_matters: `Needs-reply must come from whether a reply exists — not from a client-sent flag. One store is the single source of truth for list and create — every Review row created through /api/reviews has to still be there on the next GET, or the desk would be lying about what's actually owed, booked, or open.`,
    answer_keywords: ["reviews","nextId","nextIdCounter"],
    seed_code: `// store
`,
    starter_code: `// store
`,
    feedback_correct: "Correct — keep going.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Server owns the array.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `Two requests that arrive close together must never be handed the same id — a counter that only ever increases guarantees each new record gets a value nothing before it used, which a timestamp alone cannot promise.`,
    expected: `let reviews = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return reviews; }
`,
    analog_example: `let tasks = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `An id generator only has one job: never repeat. A timestamp looks unique but isn't — two requests in the same millisecond produce the same value and silently overwrite each other's row. A counter that only increases is a small, boring fix for a bug that is otherwise invisible until real traffic hits it.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/reviews with a derived status:

  Store    →  in-memory Review rows
  Validate →  required fields
  Derive   →  if replied true → answered; else needs-reply
  Routes   →  GET/POST attach computed status (do not trust client status)`,
      discover: `let reviews = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return reviews; }
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `let reviews = []; let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }`,
    },
  },
  {
    id: "step2",
    type: "question",
    phase: "Step 2 of 4",
    paal: `Validate required fields before creating a record

SAMPLE — /api/reviews
POST /api/reviews
{ …fields… }

Your task: write validateReview(input) that returns an error string when a required field is missing/invalid, else null.`,
    hint: `validateReview returns error string or null.`,
    example_code: `if (!input?.title?.trim()) return "title is required";`,
    think_prompt: `\`\`\`text
SAMPLE — /api/reviews
POST /api/reviews
{ …fields… }
→ 201 created  OR  400 bad request
\`\`\`

Whatever a client sends in a request body can never be assumed well-formed — checking for missing or malformed fields before anything else runs is what keeps bad data from ever reaching storage. What must be true about the fields above before you insert a row?`,
    mc_options: ["error string for bad fields, else null","accept any JSON","coerce everything to strings silently"],
    mc_correct_option: "error string for bad fields, else null",
    mc_anchor: "error string for bad fields, else null",
    why_this_matters: `Validation keeps junk out of the store before status is ever derived from it. Needs-reply must come from whether a reply exists — not from a client-sent flag.`,
    answer_keywords: ["validateReview","author","rating","body","postedAt"],
    seed_code: `let reviews = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
`,
    starter_code: `let reviews = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validateReview(input) {}
`,
    feedback_correct: "Correct — keep going.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Validate first.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `A validator is just a function that inspects the fields it was given and returns either a short error message or nothing at all — the caller decides what to do with that answer.`,
    expected: `let reviews = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return reviews; }
export function validateReview(input) {
  if (typeof input?.author !== "string" || !input.author.trim()) return "author is required";
  if (typeof input?.rating !== "number" || input.rating <= 0) return "rating must be > 0";
  if (typeof input?.body !== "string" || !input.body.trim()) return "body is required";
  if (typeof input?.postedAt !== "string" || !input.postedAt.trim()) return "postedAt is required";
  return null;
}
`,
    analog_example: `if (!input?.title?.trim()) return "title is required";`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `Validation that returns an error string (instead of throwing, or silently coercing) is what lets a route reply with a specific 400 message instead of crashing or quietly storing garbage. Run it once, in one function, so every route into this resource gets the same guarantee.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/reviews with a derived status:

  Store    →  in-memory Review rows
  Validate →  required fields
  Derive   →  if replied true → answered; else needs-reply
  Routes   →  GET/POST attach computed status (do not trust client status)`,
      discover: `let reviews = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function getStore() { return reviews; }
export function validateReview(input) {
  if (typeof input?.author !== "string" || !input.author.trim()) return "author is required";
  if (typeof input?.rating !== "number" || input.rating <= 0) return "rating must be > 0";
  if (typeof input?.body !== "string" || !input.body.trim()) return "body is required";
  if (typeof input?.postedAt !== "string" || !input.postedAt.trim()) return "postedAt is required";
  return null;
}
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `validateReview returns error string or null.`,
    },
  },
  {
    id: "step3",
    type: "question",
    phase: "Step 3 of 4",
    paal: `Derive a status from stored data instead of trusting the request body

SAMPLE — /api/reviews
Rule: if replied true → answered; else needs-reply

Your task: write deriveReviewStatus(row, now) that returns the status string computed from the rule above — never from req.body.`,
    hint: `deriveReviewStatus(row, now) returns the status string.`,
    example_code: `function taskStatus(item, today) {
  if (item.done) return "done";
  if (new Date(item.due) < today) return "late";
  return "open";
}`,
    think_prompt: `\`\`\`text
SAMPLE — /api/reviews
GET /api/reviews
→ [ { "id": "1", "status": "…" } ]

Rule: if replied true → answered; else needs-reply
\`\`\`

A status label describing a record can always be recalculated from that record's own stored facts — comparing dates, or checking a boolean flag — rather than being sent by the client and simply trusted. Given the rule above, should the browser send status, or should the server compute it — and from what?`,
    mc_options: ["server derives status from stored facts; ignore client status","save req.body.status as-is","randomize status on every GET"],
    mc_correct_option: "server derives status from stored facts; ignore client status",
    mc_anchor: "server derives status from stored facts;",
    why_this_matters: `The browser can send anything; computing status from facts you already trust is what keeps it from being faked. Needs-reply must come from whether a reply exists — not from a client-sent flag.`,
    answer_keywords: ["deriveReviewStatus"],
    seed_code: `let reviews = [];
export function validateReview(input) { return null; }
`,
    starter_code: `let reviews = [];
export function validateReview(input) { return null; }
export function deriveReviewStatus(row, now = new Date()) {}
`,
    feedback_correct: "Correct — keep going.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Status is computed on the server.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `A derive function takes one stored row (plus, optionally, the current time) and returns a label computed purely from that row's own fields — it never reads anything the client sent in the current request.`,
    expected: `let reviews = [];
export function validateReview(input) { return null; }
export function deriveReviewStatus(row, now = new Date()) {
  if (row.replied === true) return "answered";
  if (new Date(row.rating) < now) return "needs-reply";
  return "needs-reply";
}
`,
    analog_example: `function taskStatus(item, today) {
  if (item.done) return "done";
  if (new Date(item.due) < today) return "late";
  return "open";
}`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `A derived field only stays honest if it is recomputed from source facts every single time it's read, not stored and trusted. The moment a status is written once and reused, it can drift from the facts that produced it — a client-sent status has that problem from the very first request.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/reviews with a derived status:

  Store    →  in-memory Review rows
  Validate →  required fields
  Derive   →  if replied true → answered; else needs-reply
  Routes   →  GET/POST attach computed status (do not trust client status)`,
      discover: `let reviews = [];
export function validateReview(input) { return null; }
export function deriveReviewStatus(row, now = new Date()) {
  if (row.replied === true) return "answered";
  if (new Date(row.rating) < now) return "needs-reply";
  return "needs-reply";
}
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `deriveReviewStatus(row, now) returns the status string.`,
    },
  },
  {
    id: "step4",
    type: "question",
    phase: "Step 4 of 4",
    paal: `Implement GET to list records and POST to create, attaching the derived status

SAMPLE — /api/reviews
GET → rows + status  ·  POST → 201 + status

Your task: wire list() to map deriveReviewStatus over reviews, and create() to validate, push, then return the row with deriveReviewStatus attached.`,
    hint: `list: reviews.map(r => ({...r, status: deriveReviewStatus(r)}))`,
    example_code: `res.json(tasks.map((t) => ({ ...t, status: taskStatus(t) })));`,
    think_prompt: `\`\`\`text
SAMPLE — /api/reviews
GET /api/reviews
→ [ …rows with status ]

POST /api/reviews
→ 201 { …row, "status": "…" }
\`\`\`

Attaching a computed field to data on its way out of a route means running the derive function once per record, every time that record is returned — never once at write time and then reused. How do GET and POST above reuse validateReview and deriveReviewStatus to guarantee status is never stale?`,
    mc_options: ["GET/POST attach derived status; POST validates first","POST stores client status verbatim","GET omits status"],
    mc_correct_option: "GET/POST attach derived status; POST validates first",
    mc_anchor: "GET/POST attach derived status; POST val",
    why_this_matters: `Always attach derive on the way out — POST validates, inserts, then attaches status, exactly like GET does. Needs-reply must come from whether a reply exists — not from a client-sent flag.`,
    answer_keywords: ["deriveReviewStatus","validateReview","201"],
    seed_code: `let reviews = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validateReview(input) { return null; }
export function deriveReviewStatus(row, now = new Date()) { return "open"; }
`,
    starter_code: `let reviews = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validateReview(input) { return null; }
export function deriveReviewStatus(row, now = new Date()) { return "open"; }
export function createHandlers() {
  return { list() {}, create() {} };
}
`,
    feedback_correct: "Correct — list and create attach derived status.",
    feedback_partial: "Close — check the hint and try again.",
    feedback_wrong: "Always derive on the way out.",
    // Fix 2: shown pre-check (before CHECK MY CODE has run on this step) instead of the
    // generic fallback feedback text — a lightweight, non-answer-revealing conceptual hint.
    pre_check_hint: `A route handler's job is to call helpers in the right order and translate their answers into HTTP responses — validate first, then map the derive function over whatever gets returned.`,
    expected: `let reviews = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validateReview(input) { return null; }
export function deriveReviewStatus(row, now = new Date()) { return "open"; }
export function createHandlers() {
  return {
    list(_req, res) {
      res.json(reviews.map((r) => ({ ...r, status: deriveReviewStatus(r) })));
    },
    create(req, res) {
      const err = validateReview(req.body);
      if (err) return res.status(400).json({ error: err });
      const row = { id: nextId(), author: req.body.author, rating: req.body.rating, body: req.body.body, postedAt: req.body.postedAt, replied: false };
      reviews.push(row);
      res.status(201).json({ ...row, status: deriveReviewStatus(row) });
    },
  };
}
`,
    analog_example: `res.json(tasks.map((t) => ({ ...t, status: taskStatus(t) })));`,
    deepDiveLabel: "Why this step matters",
    deepDive: {
      // Fix 7: lead with the general concept (why a shared pattern matters), not the task
      // instruction restated verbatim.
      hook: `The rule "always derive on the way out" means the same map-over-derive call appears in both GET and POST — there is no separate code path where status could accidentally be skipped or hard-coded. Consistency here is what keeps the API honest under every route that touches this resource.`,
      pain: "Skipping this step leaves later code with no data shape or no source of truth.",
      mentalModel: `Implement /api/reviews with a derived status:

  Store    →  in-memory Review rows
  Validate →  required fields
  Derive   →  if replied true → answered; else needs-reply
  Routes   →  GET/POST attach computed status (do not trust client status)`,
      discover: `let reviews = [];
let nextIdCounter = 1;
function nextId() { return String(nextIdCounter++); }
export function validateReview(input) { return null; }
export function deriveReviewStatus(row, now = new Date()) { return "open"; }
export function createHandlers() {
  return {
    list(_req, res) {
      res.json(reviews.map((r) => ({ ...r, status: deriveReviewStatus(r) })));
    },
    create(req, res) {
      const err = validateReview(req.body);
      if (err) return res.status(400).json({ error: err });
      const row = { id: nextId(), author: req.body.author, rating: req.body.rating, body: req.body.body, postedAt: req.body.postedAt, replied: false };
      reviews.push(row);
      res.status(201).json({ ...row, status: deriveReviewStatus(row) });
    },
  };
}
`,
      quickRules: "- One skill per step\n- Name the skill, not the product noun\n- Example uses the same pattern",
      watchOut: "Do not turn a single import or interface into its own lesson.",
      dryRun: "Write the same step for a different resource with the same shape.",
      build: `list: reviews.map(r => ({...r, status: deriveReviewStatus(r)}))`,
    },
  },
];

const sideItems = [
  { label: "Lesson", id: "intro" },
  { label: "Objectives", id: "objectives" },
  { label: "Step 1", id: "step1" },
  { label: "Step 2", id: "step2" },
  { label: "Step 3", id: "step3" },
  { label: "Step 4", id: "step4" },
];

export default createINPACTEngine({
  NODES,
  sideItems,
  lessonNum: 0,
  title: "Reviews API with needs-reply status",
  shortName: "Review API",
});
